/////////////////////////////////////////////////////////////////////////////////
// File : Engine/Rendering/DeviceRenderer.h
/////////////////////////////////////////////////////////////////////////////////
// Version : 1.0a
// Began Code : 29/05/2010
// Status : Alpha
// Portability : Any
/////////////////////////////////////////////////////////////////////////////////
// Description : Wrapper for system-dependant third party API selection.
/////////////////////////////////////////////////////////////////////////////////
// Part of Scarab-Engine, licensed under the
// Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License
//   http://creativecommons.org/licenses/by-nc-nd/3.0/
/////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////
// Known Bugs : None.
/////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////
// Header prelude
#ifndef SCARAB_ENGINE_RENDERING_DEVICERENDERER_H
#define SCARAB_ENGINE_RENDERING_DEVICERENDERER_H

/////////////////////////////////////////////////////////////////////////////////
// Conditional compilation flags
#define RENDERER_USE_DIRECT3D11
//#define RENDERER_USE_OPENGL
//#define RENDERER_USE_SOFTWARE

/////////////////////////////////////////////////////////////////////////////////
// Includes
#if defined(RENDERER_USE_DIRECT3D11)
/////////////////////////////////////////////////////////////////////////////////

    #include "../../ThirdParty/DirectX11/Direct3D/D3D11Renderer.h"
    #include "../../ThirdParty/DirectX11/Direct3D/2D/D2D1RenderingContext.h"

#elif defined(RENDERER_USE_OPENGL)
/////////////////////////////////////////////////////////////////////////////////

    /////////////////////////////////////////////////////////

#elif defined(RENDERER_USE_SOFTWARE)
/////////////////////////////////////////////////////////////////////////////////

    /////////////////////////////////////////////////////////

#endif

/////////////////////////////////////////////////////////////////////////////////
// Device Definitions
#if defined(RENDERER_USE_DIRECT3D11)
/////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////
// DeviceWindow Definitions
typedef D3D11Point2    DevicePoint2;
typedef D3D11Point3    DevicePoint3;
typedef D3D11Rectangle DeviceRectangle;
typedef D3D11Box       DeviceBox;
typedef D3D11Viewport  DeviceViewport;

#define DEVICEWINDOW_TITLE_SIZE       D3D11WINDOW_TITLE_SIZE

#define DEVICEWINDOW_MIN_WIDTH        D3D11WINDOW_MIN_WIDTH
#define DEVICEWINDOW_MIN_HEIGHT       D3D11WINDOW_MIN_HEIGHT

#define DEVICEWINDOW_MAX_ADAPTERS     D3D11WINDOW_MAX_ADAPTERS
#define DEVICEWINDOW_MAX_OUTPUTS      D3D11WINDOW_MAX_OUTPUTS
#define DEVICEWINDOW_MAX_DISPLAYMODES D3D11WINDOW_MAX_DISPLAYMODES

typedef D3D11AdapterDesc DeviceAdapterDesc;

typedef D3D11OutputRotation             DeviceOutputRotation;
#define DEVICEOUTPUT_ROTATION_UNDEFINED D3D11OUTPUT_ROTATION_UNDEFINED
#define DEVICEOUTPUT_ROTATION_IDENTITY  D3D11OUTPUT_ROTATION_IDENTITY
#define DEVICEOUTPUT_ROTATION_90        D3D11OUTPUT_ROTATION_90
#define DEVICEOUTPUT_ROTATION_180       D3D11OUTPUT_ROTATION_180
#define DEVICEOUTPUT_ROTATION_270       D3D11OUTPUT_ROTATION_270

typedef D3D11OutputDesc DeviceOutputDesc;

typedef D3D11GammaCaps    DeviceGammaCaps;
typedef D3D11GammaControl DeviceGammaControl;

typedef D3D11DisplayModeScanlineOrdering             DeviceDisplayModeScanlineOrdering;
#define DEVICEDISPLAYMODE_SCANLINE_UNDEFINED         D3D11DISPLAYMODE_SCANLINE_UNDEFINED
#define DEVICEDISPLAYMODE_SCANLINE_PROGRESSIVE       D3D11DISPLAYMODE_SCANLINE_PROGRESSIVE
#define DEVICEDISPLAYMODE_SCANLINE_UPPER_FIELD_FIRST D3D11DISPLAYMODE_SCANLINE_UPPER_FIELD_FIRST
#define DEVICEDISPLAYMODE_SCANLINE_LOWER_FIELD_FIRST D3D11DISPLAYMODE_SCANLINE_LOWER_FIELD_FIRST

typedef D3D11DisplayModeScaling             DeviceDisplayModeScaling;
#define DEVICEDISPLAYMODE_SCALING_UNDEFINED D3D11DISPLAYMODE_SCALING_UNDEFINED
#define DEVICEDISPLAYMODE_SCALING_CENTERED  D3D11DISPLAYMODE_SCALING_CENTERED
#define DEVICEDISPLAYMODE_SCALING_STRETCHED D3D11DISPLAYMODE_SCALING_STRETCHED

typedef D3D11DisplayModeDesc DeviceDisplayModeDesc;

typedef D3D11WindowCallbacks DeviceWindowCallbacks;
typedef D3D11Window          DeviceWindow;

/////////////////////////////////////////////////////////////////////////////////
// DeviceRenderer Definitions
#define DEVICERENDERER_MAX_VERTEXBUFFER_SLOTS     D3D11RENDERER_MAX_VERTEXBUFFER_SLOTS
#define DEVICERENDERER_MAX_CONSTANTBUFFER_SLOTS   D3D11RENDERER_MAX_CONSTANTBUFFER_SLOTS
#define DEVICERENDERER_MAX_SHADERSAMPLER_SLOTS    D3D11RENDERER_MAX_SHADERSAMPLER_SLOTS
#define DEVICERENDERER_MAX_SHADERRESOURCE_SLOTS   D3D11RENDERER_MAX_SHADERRESOURCE_SLOTS
#define DEVICERENDERER_MAX_STREAMOUTPUT_SLOTS     D3D11RENDERER_MAX_STREAMOUTPUT_SLOTS
#define DEVICERENDERER_MAX_VIEWPORT_SCISSOR_SLOTS D3D11RENDERER_MAX_VIEWPORT_SCISSOR_SLOTS
#define DEVICERENDERER_MAX_RENDERTARGET_SLOTS     D3D11RENDERER_MAX_RENDERTARGET_SLOTS
#define DEVICERENDERER_MAX_SHADERUAV_SLOTS        D3D11RENDERER_MAX_SHADERUAV_SLOTS
#define DEVICERENDERER_MAX_OUTPUTUAV_SLOTS        D3D11RENDERER_MAX_OUTPUTUAV_SLOTS

#define DEVICERENDERER_MAX_SWAPCHAIN_BUFFERS         D3D11RENDERER_MAX_SWAPCHAIN_BUFFERS
#define DEVICERENDERER_MAX_STREAMOUTPUT_DECLARATIONS D3D11RENDERER_MAX_STREAMOUTPUT_DECLARATIONS

typedef D3D11PixelFormatSupportFlags1                          DevicePixelFormatSupportFlags1;
#define DEVICEPIXELFORMAT_SUPPORT1_NONE                        D3D11PIXELFORMAT_SUPPORT1_NONE
#define DEVICEPIXELFORMAT_SUPPORT1_BUFFER                      D3D11PIXELFORMAT_SUPPORT1_BUFFER
#define DEVICEPIXELFORMAT_SUPPORT1_IA_VERTEX_BUFFER            D3D11PIXELFORMAT_SUPPORT1_IA_VERTEX_BUFFER
#define DEVICEPIXELFORMAT_SUPPORT1_IA_INDEX_BUFFER             D3D11PIXELFORMAT_SUPPORT1_IA_INDEX_BUFFER
#define DEVICEPIXELFORMAT_SUPPORT1_SO_BUFFER                   D3D11PIXELFORMAT_SUPPORT1_SO_BUFFER
#define DEVICEPIXELFORMAT_SUPPORT1_TEXTURE1D                   D3D11PIXELFORMAT_SUPPORT1_TEXTURE1D
#define DEVICEPIXELFORMAT_SUPPORT1_TEXTURE2D                   D3D11PIXELFORMAT_SUPPORT1_TEXTURE2D
#define DEVICEPIXELFORMAT_SUPPORT1_TEXTURE3D                   D3D11PIXELFORMAT_SUPPORT1_TEXTURE3D
#define DEVICEPIXELFORMAT_SUPPORT1_TEXTURECUBE                 D3D11PIXELFORMAT_SUPPORT1_TEXTURECUBE
#define DEVICEPIXELFORMAT_SUPPORT1_SHADER_LOAD                 D3D11PIXELFORMAT_SUPPORT1_SHADER_LOAD
#define DEVICEPIXELFORMAT_SUPPORT1_SHADER_SAMPLE               D3D11PIXELFORMAT_SUPPORT1_SHADER_SAMPLE
#define DEVICEPIXELFORMAT_SUPPORT1_SHADER_SAMPLE_COMPARISON    D3D11PIXELFORMAT_SUPPORT1_SHADER_SAMPLE_COMPARISON
#define DEVICEPIXELFORMAT_SUPPORT1_SHADER_SAMPLE_MONO_TEXT     D3D11PIXELFORMAT_SUPPORT1_SHADER_SAMPLE_MONO_TEXT
#define DEVICEPIXELFORMAT_SUPPORT1_MIP                         D3D11PIXELFORMAT_SUPPORT1_MIP
#define DEVICEPIXELFORMAT_SUPPORT1_MIP_AUTOGEN                 D3D11PIXELFORMAT_SUPPORT1_MIP_AUTOGEN
#define DEVICEPIXELFORMAT_SUPPORT1_RENDER_TARGET               D3D11PIXELFORMAT_SUPPORT1_RENDER_TARGET
#define DEVICEPIXELFORMAT_SUPPORT1_BLENDABLE                   D3D11PIXELFORMAT_SUPPORT1_BLENDABLE
#define DEVICEPIXELFORMAT_SUPPORT1_DEPTH_STENCIL               D3D11PIXELFORMAT_SUPPORT1_DEPTH_STENCIL
#define DEVICEPIXELFORMAT_SUPPORT1_CPU_LOCKABLE                D3D11PIXELFORMAT_SUPPORT1_CPU_LOCKABLE
#define DEVICEPIXELFORMAT_SUPPORT1_MULTISAMPLE_RESOLVE         D3D11PIXELFORMAT_SUPPORT1_MULTISAMPLE_RESOLVE
#define DEVICEPIXELFORMAT_SUPPORT1_DISPLAY                     D3D11PIXELFORMAT_SUPPORT1_DISPLAY
#define DEVICEPIXELFORMAT_SUPPORT1_CAST_WITHIN_BIT_LAYOUT      D3D11PIXELFORMAT_SUPPORT1_CAST_WITHIN_BIT_LAYOUT
#define DEVICEPIXELFORMAT_SUPPORT1_MULTISAMPLE_RENDERTARGET    D3D11PIXELFORMAT_SUPPORT1_MULTISAMPLE_RENDERTARGET
#define DEVICEPIXELFORMAT_SUPPORT1_MULTISAMPLE_LOAD            D3D11PIXELFORMAT_SUPPORT1_MULTISAMPLE_LOAD
#define DEVICEPIXELFORMAT_SUPPORT1_SHADER_GATHER               D3D11PIXELFORMAT_SUPPORT1_SHADER_GATHER
#define DEVICEPIXELFORMAT_SUPPORT1_BACK_BUFFER_CAST            D3D11PIXELFORMAT_SUPPORT1_BACK_BUFFER_CAST
#define DEVICEPIXELFORMAT_SUPPORT1_TYPED_UNORDERED_ACCESS_VIEW D3D11PIXELFORMAT_SUPPORT1_TYPED_UNORDERED_ACCESS_VIEW
#define DEVICEPIXELFORMAT_SUPPORT1_SHADER_GATHER_COMPARISON    D3D11PIXELFORMAT_SUPPORT1_SHADER_GATHER_COMPARISON
#define DEVICEPIXELFORMAT_SUPPORT1_DECODER_OUTPUT              D3D11PIXELFORMAT_SUPPORT1_DECODER_OUTPUT
#define DEVICEPIXELFORMAT_SUPPORT1_VIDEO_PROCESSOR_OUTPUT      D3D11PIXELFORMAT_SUPPORT1_VIDEO_PROCESSOR_OUTPUT
#define DEVICEPIXELFORMAT_SUPPORT1_VIDEO_PROCESSOR_INPUT       D3D11PIXELFORMAT_SUPPORT1_VIDEO_PROCESSOR_INPUT
#define DEVICEPIXELFORMAT_SUPPORT1_VIDEO_ENCODER               D3D11PIXELFORMAT_SUPPORT1_VIDEO_ENCODER

typedef D3D11PixelFormatSupportFlags2                                           DevicePixelFormatSupportFlags2;
#define DEVICEPIXELFORMAT_SUPPORT2_NONE                                         D3D11PIXELFORMAT_SUPPORT2_NONE
#define DEVICEPIXELFORMAT_SUPPORT2_UAV_ATOMIC_ADD                               D3D11PIXELFORMAT_SUPPORT2_UAV_ATOMIC_ADD
#define DEVICEPIXELFORMAT_SUPPORT2_UAV_ATOMIC_BITWISE_OPS                       D3D11PIXELFORMAT_SUPPORT2_UAV_ATOMIC_BITWISE_OPS
#define DEVICEPIXELFORMAT_SUPPORT2_UAV_ATOMIC_COMPARE_STORE_OR_COMPARE_EXCHANGE D3D11PIXELFORMAT_SUPPORT2_UAV_ATOMIC_COMPARE_STORE_OR_COMPARE_EXCHANGE
#define DEVICEPIXELFORMAT_SUPPORT2_UAV_ATOMIC_EXCHANGE                          D3D11PIXELFORMAT_SUPPORT2_UAV_ATOMIC_EXCHANGE
#define DEVICEPIXELFORMAT_SUPPORT2_UAV_ATOMIC_SIGNED_MIN_OR_MAX                 D3D11PIXELFORMAT_SUPPORT2_UAV_ATOMIC_SIGNED_MIN_OR_MAX
#define DEVICEPIXELFORMAT_SUPPORT2_UAV_ATOMIC_UNSIGNED_MIN_OR_MAX               D3D11PIXELFORMAT_SUPPORT2_UAV_ATOMIC_UNSIGNED_MIN_OR_MAX
#define DEVICEPIXELFORMAT_SUPPORT2_UAV_TYPED_LOAD                               D3D11PIXELFORMAT_SUPPORT2_UAV_TYPED_LOAD
#define DEVICEPIXELFORMAT_SUPPORT2_UAV_TYPED_STORE                              D3D11PIXELFORMAT_SUPPORT2_UAV_TYPED_STORE
#define DEVICEPIXELFORMAT_SUPPORT2_OUTPUT_MERGER_LOGIC_OP                       D3D11PIXELFORMAT_SUPPORT2_OUTPUT_MERGER_LOGIC_OP

typedef D3D11PixelFormatSupport DevicePixelFormatSupport;
typedef D3D11CounterSupport     DeviceCounterSupport;

typedef D3D11DeviceFeatures DeviceDeviceFeatures;

typedef D3D11SwapChainSwapEffect                   DeviceSwapChainSwapEffect;
#define DEVICESWAPCHAIN_SWAPEFFECT_DISCARD         D3D11SWAPCHAIN_SWAPEFFECT_DISCARD
#define DEVICESWAPCHAIN_SWAPEFFECT_SEQUENTIAL      D3D11SWAPCHAIN_SWAPEFFECT_SEQUENTIAL
#define DEVICESWAPCHAIN_SWAPEFFECT_FLIP            D3D11SWAPCHAIN_SWAPEFFECT_FLIP
#define DEVICESWAPCHAIN_SWAPEFFECT_FLIP_SEQUENTIAL D3D11SWAPCHAIN_SWAPEFFECT_FLIP_SEQUENTIAL

typedef D3D11SwapChainBufferUsageFlags                       DeviceSwapChainBufferUsageFlags;
#define DEVICESWAPCHAIN_BUFFERUSAGE_NONE                 D3D11SWAPCHAIN_BUFFERUSAGE_NONE
#define DEVICESWAPCHAIN_BUFFERUSAGE_SHADER_INPUT         D3D11SWAPCHAIN_BUFFERUSAGE_SHADER_INPUT
#define DEVICESWAPCHAIN_BUFFERUSAGE_RENDER_TARGET_OUTPUT D3D11SWAPCHAIN_BUFFERUSAGE_RENDER_TARGET_OUTPUT
#define DEVICESWAPCHAIN_BUFFERUSAGE_BACK_BUFFER          D3D11SWAPCHAIN_BUFFERUSAGE_BACK_BUFFER
#define DEVICESWAPCHAIN_BUFFERUSAGE_SHARED               D3D11SWAPCHAIN_BUFFERUSAGE_SHARED
#define DEVICESWAPCHAIN_BUFFERUSAGE_READ_ONLY            D3D11SWAPCHAIN_BUFFERUSAGE_READ_ONLY
#define DEVICESWAPCHAIN_BUFFERUSAGE_DISCARD_ON_PRESENT   D3D11SWAPCHAIN_BUFFERUSAGE_DISCARD_ON_PRESENT
#define DEVICESWAPCHAIN_BUFFERUSAGE_UNORDERED_ACCESS     D3D11SWAPCHAIN_BUFFERUSAGE_UNORDERED_ACCESS

typedef D3D11SwapChainFlags                                  DeviceSwapChainFlags;
#define DEVICESWAPCHAIN_FLAG_NONE                            D3D11SWAPCHAIN_FLAG_NONE
#define DEVICESWAPCHAIN_FLAG_NONPREROTATED                   D3D11SWAPCHAIN_FLAG_NONPREROTATED
#define DEVICESWAPCHAIN_FLAG_ALLOW_MODE_SWITCH               D3D11SWAPCHAIN_FLAG_ALLOW_MODE_SWITCH
#define DEVICESWAPCHAIN_FLAG_GDI_COMPATIBLE                  D3D11SWAPCHAIN_FLAG_GDI_COMPATIBLE
#define DEVICESWAPCHAIN_FLAG_RESTRICTED_CONTENT              D3D11SWAPCHAIN_FLAG_RESTRICTED_CONTENT
#define DEVICESWAPCHAIN_FLAG_RESTRICT_SHARED_RESOURCE_DRIVER D3D11SWAPCHAIN_FLAG_RESTRICT_SHARED_RESOURCE_DRIVER
#define DEVICESWAPCHAIN_FLAG_DISPLAY_ONLY                    D3D11SWAPCHAIN_FLAG_DISPLAY_ONLY

typedef D3D11SwapChainDesc DeviceSwapChainDesc;

typedef D3D11PresentFlags                      DevicePresentFlags;
#define DEVICEPRESENT_FLAG_NONE                D3D11PRESENT_FLAG_NONE
//#define DEVICEPRESENT_FLAG_TEST                D3D11PRESENT_FLAG_TEST // Never expose to the app, we manage this internally
#define DEVICEPRESENT_FLAG_DONT_SEQUENCE       D3D11PRESENT_FLAG_DONT_SEQUENCE
#define DEVICEPRESENT_FLAG_RESTART             D3D11PRESENT_FLAG_RESTART
#define DEVICEPRESENT_FLAG_DONT_WAIT           D3D11PRESENT_FLAG_DONT_WAIT
#define DEVICEPRESENT_FLAG_STEREO_PREFER_RIGHT D3D11PRESENT_FLAG_STEREO_PREFER_RIGHT
#define DEVICEPRESENT_FLAG_STEREO_TEMP_MONO    D3D11PRESENT_FLAG_STEREO_TEMP_MONO
#define DEVICEPRESENT_FLAG_RESTRICT_TO_OUTPUT  D3D11PRESENT_FLAG_RESTRICT_TO_OUTPUT

typedef D3D11FrameStats DeviceFrameStats;

typedef D3D11RendererCallbacks DeviceRendererCallbacks;
typedef D3D11Renderer          DeviceRenderer;

/////////////////////////////////////////////////////////////////////////////////
// DeviceDeferredContext Definitions
typedef D3D11CommandList     DeviceCommandList;
typedef D3D11DeferredContext DeviceDeferredContext;

/////////////////////////////////////////////////////////////////////////////////
// DeviceInputLayout Definitions
#define DEVICEINPUTLAYOUT_MAX_FIELDS    D3D11INPUTLAYOUT_MAX_FIELDS
#define DEVICEINPUTLAYOUT_MAX_COLORS    D3D11INPUTLAYOUT_MAX_COLORS
#define DEVICEINPUTLAYOUT_MAX_TEXCOORDS D3D11INPUTLAYOUT_MAX_TEXCOORDS

typedef D3D11InputFieldType        DeviceInputFieldType;
#define DEVICEINPUTFIELD_FLOAT    D3D11INPUTFIELD_FLOAT
#define DEVICEINPUTFIELD_FLOAT2   D3D11INPUTFIELD_FLOAT2
#define DEVICEINPUTFIELD_FLOAT3   D3D11INPUTFIELD_FLOAT3
#define DEVICEINPUTFIELD_FLOAT4   D3D11INPUTFIELD_FLOAT4
#define DEVICEINPUTFIELD_BYTE     D3D11INPUTFIELD_BYTE
#define DEVICEINPUTFIELD_BYTEN    D3D11INPUTFIELD_BYTEN
#define DEVICEINPUTFIELD_BYTE2    D3D11INPUTFIELD_BYTE2
#define DEVICEINPUTFIELD_BYTE2N   D3D11INPUTFIELD_BYTE2N
#define DEVICEINPUTFIELD_BYTE4    D3D11INPUTFIELD_BYTE4
#define DEVICEINPUTFIELD_BYTE4N   D3D11INPUTFIELD_BYTE4N
#define DEVICEINPUTFIELD_SSHORT   D3D11INPUTFIELD_SSHORT
#define DEVICEINPUTFIELD_SSHORTN  D3D11INPUTFIELD_SSHORTN
#define DEVICEINPUTFIELD_SSHORT2  D3D11INPUTFIELD_SSHORT2
#define DEVICEINPUTFIELD_SSHORT2N D3D11INPUTFIELD_SSHORT2N
#define DEVICEINPUTFIELD_SSHORT4  D3D11INPUTFIELD_SSHORT4
#define DEVICEINPUTFIELD_SSHORT4N D3D11INPUTFIELD_SSHORT4N
#define DEVICEINPUTFIELD_USHORT   D3D11INPUTFIELD_USHORT
#define DEVICEINPUTFIELD_USHORTN  D3D11INPUTFIELD_USHORTN
#define DEVICEINPUTFIELD_USHORT2  D3D11INPUTFIELD_USHORT2
#define DEVICEINPUTFIELD_USHORT2N D3D11INPUTFIELD_USHORT2N
#define DEVICEINPUTFIELD_USHORT4  D3D11INPUTFIELD_USHORT4
#define DEVICEINPUTFIELD_USHORT4N D3D11INPUTFIELD_USHORT4N
#define DEVICEINPUTFIELD_SINT     D3D11INPUTFIELD_SINT
#define DEVICEINPUTFIELD_SINT2    D3D11INPUTFIELD_SINT2
#define DEVICEINPUTFIELD_SINT3    D3D11INPUTFIELD_SINT3
#define DEVICEINPUTFIELD_SINT4    D3D11INPUTFIELD_SINT4
#define DEVICEINPUTFIELD_UINT     D3D11INPUTFIELD_UINT
#define DEVICEINPUTFIELD_UINT2    D3D11INPUTFIELD_UINT2
#define DEVICEINPUTFIELD_UINT3    D3D11INPUTFIELD_UINT3
#define DEVICEINPUTFIELD_UINT4    D3D11INPUTFIELD_UINT4
#define DEVICEINPUTFIELD_COUNT    D3D11INPUTFIELD_COUNT

#define DEVICEINPUTFIELD_SEMANTIC_POSITION      D3D11INPUTFIELD_SEMANTIC_POSITION
#define DEVICEINPUTFIELD_SEMANTIC_TPOSITION     D3D11INPUTFIELD_SEMANTIC_TPOSITION
#define DEVICEINPUTFIELD_SEMANTIC_NORMAL        D3D11INPUTFIELD_SEMANTIC_NORMAL
#define DEVICEINPUTFIELD_SEMANTIC_TANGENT       D3D11INPUTFIELD_SEMANTIC_TANGENT
#define DEVICEINPUTFIELD_SEMANTIC_BINORMAL      D3D11INPUTFIELD_SEMANTIC_BINORMAL
#define DEVICEINPUTFIELD_SEMANTIC_COLOR         D3D11INPUTFIELD_SEMANTIC_COLOR
#define DEVICEINPUTFIELD_SEMANTIC_TEXCOORD      D3D11INPUTFIELD_SEMANTIC_TEXCOORD
#define DEVICEINPUTFIELD_SEMANTIC_BLEND_INDICES D3D11INPUTFIELD_SEMANTIC_BLEND_INDICES
#define DEVICEINPUTFIELD_SEMANTIC_BLEND_WEIGHTS D3D11INPUTFIELD_SEMANTIC_BLEND_WEIGHTS
#define DEVICEINPUTFIELD_SEMANTIC_POINTSIZE     D3D11INPUTFIELD_SEMANTIC_POINTSIZE

typedef D3D11InputFieldSlotClass                DeviceInputFieldSlotClass;
#define DEVICEINPUTFIELD_SLOTCLASS_PER_VERTEX   D3D11INPUTFIELD_SLOTCLASS_PER_VERTEX
#define DEVICEINPUTFIELD_SLOTCLASS_PER_INSTANCE D3D11INPUTFIELD_SLOTCLASS_PER_INSTANCE

typedef D3D11InputFieldDesc DeviceInputFieldDesc;

typedef D3D11InputLayout DeviceInputLayout;

/////////////////////////////////////////////////////////////////////////////////
// DeviceRenderState Definitions
typedef D3D11RenderStateType            DeviceRenderStateType;
#define DEVICERENDERSTATE_SAMPLER      D3D11RENDERSTATE_SAMPLER
#define DEVICERENDERSTATE_RASTERIZER   D3D11RENDERSTATE_RASTERIZER
#define DEVICERENDERSTATE_DEPTHSTENCIL D3D11RENDERSTATE_DEPTHSTENCIL
#define DEVICERENDERSTATE_BLEND        D3D11RENDERSTATE_BLEND

typedef D3D11SamplerFilterMode                  DeviceSamplerFilterMode;
#define DEVICESAMPLER_FILTER_MIN_MAG_MIP_PPP    D3D11SAMPLER_FILTER_MIN_MAG_MIP_PPP
#define DEVICESAMPLER_FILTER_MIN_MAG_MIP_PPL    D3D11SAMPLER_FILTER_MIN_MAG_MIP_PPL
#define DEVICESAMPLER_FILTER_MIN_MAG_MIP_PLP    D3D11SAMPLER_FILTER_MIN_MAG_MIP_PLP
#define DEVICESAMPLER_FILTER_MIN_MAG_MIP_PLL    D3D11SAMPLER_FILTER_MIN_MAG_MIP_PLL
#define DEVICESAMPLER_FILTER_MIN_MAG_MIP_LPP    D3D11SAMPLER_FILTER_MIN_MAG_MIP_LPP
#define DEVICESAMPLER_FILTER_MIN_MAG_MIP_LPL    D3D11SAMPLER_FILTER_MIN_MAG_MIP_LPL
#define DEVICESAMPLER_FILTER_MIN_MAG_MIP_LLP    D3D11SAMPLER_FILTER_MIN_MAG_MIP_LLP
#define DEVICESAMPLER_FILTER_MIN_MAG_MIP_LLL    D3D11SAMPLER_FILTER_MIN_MAG_MIP_LLL
#define DEVICESAMPLER_FILTER_ANISOTROPIC        D3D11SAMPLER_FILTER_ANISOTROPIC
#define DEVICESAMPLER_FILTERCMP_MIN_MAG_MIP_PPP D3D11SAMPLER_FILTERCMP_MIN_MAG_MIP_PPP
#define DEVICESAMPLER_FILTERCMP_MIN_MAG_MIP_PPL D3D11SAMPLER_FILTERCMP_MIN_MAG_MIP_PPL
#define DEVICESAMPLER_FILTERCMP_MIN_MAG_MIP_PLP D3D11SAMPLER_FILTERCMP_MIN_MAG_MIP_PLP
#define DEVICESAMPLER_FILTERCMP_MIN_MAG_MIP_PLL D3D11SAMPLER_FILTERCMP_MIN_MAG_MIP_PLL
#define DEVICESAMPLER_FILTERCMP_MIN_MAG_MIP_LPP D3D11SAMPLER_FILTERCMP_MIN_MAG_MIP_LPP
#define DEVICESAMPLER_FILTERCMP_MIN_MAG_MIP_LPL D3D11SAMPLER_FILTERCMP_MIN_MAG_MIP_LPL
#define DEVICESAMPLER_FILTERCMP_MIN_MAG_MIP_LLP D3D11SAMPLER_FILTERCMP_MIN_MAG_MIP_LLP
#define DEVICESAMPLER_FILTERCMP_MIN_MAG_MIP_LLL D3D11SAMPLER_FILTERCMP_MIN_MAG_MIP_LLL
#define DEVICESAMPLER_FILTERCMP_ANISOTROPIC     D3D11SAMPLER_FILTERCMP_ANISOTROPIC

typedef D3D11SamplerWrapMode             DeviceSamplerWrapMode;
#define DEVICESAMPLER_WRAP_CLAMP         D3D11SAMPLER_WRAP_CLAMP
#define DEVICESAMPLER_WRAP_BORDER        D3D11SAMPLER_WRAP_BORDER
#define DEVICESAMPLER_WRAP_REPEAT        D3D11SAMPLER_WRAP_REPEAT
#define DEVICESAMPLER_WRAP_MIRROR_ONCE   D3D11SAMPLER_WRAP_MIRROR_ONCE
#define DEVICESAMPLER_WRAP_MIRROR_REPEAT D3D11SAMPLER_WRAP_MIRROR_REPEAT

typedef D3D11SamplerCompareFunction         DeviceSamplerCompareFunction;
#define DEVICESAMPLER_COMPARE_NEVER         D3D11SAMPLER_COMPARE_NEVER
#define DEVICESAMPLER_COMPARE_ALLWAYS       D3D11SAMPLER_COMPARE_ALLWAYS
#define DEVICESAMPLER_COMPARE_EQUAL         D3D11SAMPLER_COMPARE_EQUAL
#define DEVICESAMPLER_COMPARE_NOT_EQUAL     D3D11SAMPLER_COMPARE_NOT_EQUAL
#define DEVICESAMPLER_COMPARE_LESSER        D3D11SAMPLER_COMPARE_LESSER
#define DEVICESAMPLER_COMPARE_LESSER_EQUAL  D3D11SAMPLER_COMPARE_LESSER_EQUAL
#define DEVICESAMPLER_COMPARE_GREATER       D3D11SAMPLER_COMPARE_GREATER
#define DEVICESAMPLER_COMPARE_GREATER_EQUAL D3D11SAMPLER_COMPARE_GREATER_EQUAL

typedef D3D11SamplerStateDesc DeviceSamplerStateDesc;

typedef D3D11RasterizerFillMode         DeviceRasterizerFillMode;
#define DEVICERASTERIZER_FILL_WIREFRAME D3D11RASTERIZER_FILL_WIREFRAME
#define DEVICERASTERIZER_FILL_SOLID     D3D11RASTERIZER_FILL_SOLID

typedef D3D11RasterizerCullMode     DeviceRasterizerCullMode;
#define DEVICERASTERIZER_CULL_NONE  D3D11RASTERIZER_CULL_NONE
#define DEVICERASTERIZER_CULL_FRONT D3D11RASTERIZER_CULL_FRONT
#define DEVICERASTERIZER_CULL_BACK  D3D11RASTERIZER_CULL_BACK

typedef D3D11RasterizerStateDesc DeviceRasterizerStateDesc;

typedef D3D11DepthWriteMask        DeviceDepthWriteMask;
#define DEVICEDEPTH_WRITEMASK_ZERO D3D11DEPTH_WRITEMASK_ZERO
#define DEVICEDEPTH_WRITEMASK_ALL  D3D11DEPTH_WRITEMASK_ALL

typedef D3D11StencilOperation          DeviceStencilOperation;
#define DEVICESTENCIL_OP_KEEP          D3D11STENCIL_OP_KEEP
#define DEVICESTENCIL_OP_ZERO          D3D11STENCIL_OP_ZERO
#define DEVICESTENCIL_OP_INVERT        D3D11STENCIL_OP_INVERT
#define DEVICESTENCIL_OP_REPLACE       D3D11STENCIL_OP_REPLACE
#define DEVICESTENCIL_OP_INCREMENT     D3D11STENCIL_OP_INCREMENT
#define DEVICESTENCIL_OP_INCREMENT_SAT D3D11STENCIL_OP_INCREMENT_SAT
#define DEVICESTENCIL_OP_DECREMENT     D3D11STENCIL_OP_DECREMENT
#define DEVICESTENCIL_OP_DECREMENT_SAT D3D11STENCIL_OP_DECREMENT_SAT

typedef D3D11DepthStencilCompareFunction         DeviceDepthStencilCompareFunction;
#define DEVICEDEPTHSTENCIL_COMPARE_NEVER         D3D11DEPTHSTENCIL_COMPARE_NEVER
#define DEVICEDEPTHSTENCIL_COMPARE_ALLWAYS       D3D11DEPTHSTENCIL_COMPARE_ALLWAYS
#define DEVICEDEPTHSTENCIL_COMPARE_EQUAL         D3D11DEPTHSTENCIL_COMPARE_EQUAL
#define DEVICEDEPTHSTENCIL_COMPARE_NOT_EQUAL     D3D11DEPTHSTENCIL_COMPARE_NOT_EQUAL
#define DEVICEDEPTHSTENCIL_COMPARE_LESSER        D3D11DEPTHSTENCIL_COMPARE_LESSER
#define DEVICEDEPTHSTENCIL_COMPARE_LESSER_EQUAL  D3D11DEPTHSTENCIL_COMPARE_LESSER_EQUAL
#define DEVICEDEPTHSTENCIL_COMPARE_GREATER       D3D11DEPTHSTENCIL_COMPARE_GREATER
#define DEVICEDEPTHSTENCIL_COMPARE_GREATER_EQUAL D3D11DEPTHSTENCIL_COMPARE_GREATER_EQUAL

typedef D3D11DepthStencilStateDesc DeviceDepthStencilStateDesc;

typedef D3D11BlendParameter               DeviceBlendParameter;
#define DEVICEBLEND_PARAM_ZERO            D3D11BLEND_PARAM_ZERO
#define DEVICEBLEND_PARAM_ONE             D3D11BLEND_PARAM_ONE
#define DEVICEBLEND_PARAM_SRC_COLOR       D3D11BLEND_PARAM_SRC_COLOR
#define DEVICEBLEND_PARAM_SRC_COLOR_INV   D3D11BLEND_PARAM_SRC_COLOR_INV
#define DEVICEBLEND_PARAM_SRC_ALPHA       D3D11BLEND_PARAM_SRC_ALPHA
#define DEVICEBLEND_PARAM_SRC_ALPHA_INV   D3D11BLEND_PARAM_SRC_ALPHA_INV
#define DEVICEBLEND_PARAM_SRC_ALPHA_SAT   D3D11BLEND_PARAM_SRC_ALPHA_SAT
#define DEVICEBLEND_PARAM_DST_COLOR       D3D11BLEND_PARAM_DST_COLOR
#define DEVICEBLEND_PARAM_DST_COLOR_INV   D3D11BLEND_PARAM_DST_COLOR_INV
#define DEVICEBLEND_PARAM_DST_ALPHA       D3D11BLEND_PARAM_DST_ALPHA
#define DEVICEBLEND_PARAM_DST_ALPHA_INV   D3D11BLEND_PARAM_DST_ALPHA_INV
#define DEVICEBLEND_PARAM_BLENDFACTOR     D3D11BLEND_PARAM_BLENDFACTOR
#define DEVICEBLEND_PARAM_BLENDFACTOR_INV D3D11BLEND_PARAM_BLENDFACTOR_INV
#define DEVICEBLEND_PARAM_SRC1_COLOR      D3D11BLEND_PARAM_SRC1_COLOR
#define DEVICEBLEND_PARAM_SRC1_COLOR_INV  D3D11BLEND_PARAM_SRC1_COLOR_INV
#define DEVICEBLEND_PARAM_SRC1_ALPHA      D3D11BLEND_PARAM_SRC1_ALPHA
#define DEVICEBLEND_PARAM_SRC1_ALPHA_INV  D3D11BLEND_PARAM_SRC1_ALPHA_INV

typedef D3D11BlendOperation    DeviceBlendOperation;
#define DEVICEBLEND_OP_ADD     D3D11BLEND_OP_ADD
#define DEVICEBLEND_OP_SUB     D3D11BLEND_OP_SUB
#define DEVICEBLEND_OP_SUB_REV D3D11BLEND_OP_SUB_REV
#define DEVICEBLEND_OP_MIN     D3D11BLEND_OP_MIN
#define DEVICEBLEND_OP_MAX     D3D11BLEND_OP_MAX

typedef D3D11BlendColorWriteMask         DeviceBlendColorWriteMask;
#define DEVICEBLEND_COLORWRITEMASK_RED   D3D11BLEND_COLORWRITEMASK_RED
#define DEVICEBLEND_COLORWRITEMASK_GREEN D3D11BLEND_COLORWRITEMASK_GREEN
#define DEVICEBLEND_COLORWRITEMASK_BLUE  D3D11BLEND_COLORWRITEMASK_BLUE
#define DEVICEBLEND_COLORWRITEMASK_ALPHA D3D11BLEND_COLORWRITEMASK_ALPHA
#define DEVICEBLEND_COLORWRITEMASK_ALL   D3D11BLEND_COLORWRITEMASK_ALL

typedef D3D11BlendStateDesc DeviceBlendStateDesc;

typedef D3D11RenderState       DeviceRenderState;
typedef D3D11SamplerState      DeviceSamplerState;
typedef D3D11RasterizerState   DeviceRasterizerState;
typedef D3D11DepthStencilState DeviceDepthStencilState;
typedef D3D11BlendState        DeviceBlendState;

/////////////////////////////////////////////////////////////////////////////////
// DeviceAsynchronous Definitions
typedef D3D11AsynchronousType        DeviceAsynchronousType;
#define DEVICEASYNCHRONOUS_QUERY     D3D11ASYNCHRONOUS_QUERY
#define DEVICEASYNCHRONOUS_PREDICATE D3D11ASYNCHRONOUS_PREDICATE
#define DEVICEASYNCHRONOUS_COUNTER   D3D11ASYNCHRONOUS_COUNTER

typedef D3D11QueryType                   DeviceQueryType;
#define DEVICEQUERY_EVENT                D3D11QUERY_EVENT
#define DEVICEQUERY_OCCLUSION            D3D11QUERY_OCCLUSION
#define DEVICEQUERY_TIMESTAMP_FREQUENCY  D3D11QUERY_TIMESTAMP_FREQUENCY
#define DEVICEQUERY_TIMESTAMP            D3D11QUERY_TIMESTAMP
#define DEVICEQUERY_STATS_PIPELINE       D3D11QUERY_STATS_PIPELINE
#define DEVICEQUERY_STATS_STREAMOUTPUT   D3D11QUERY_STATS_STREAMOUTPUT
#define DEVICEQUERY_STATS_STREAMOUTPUT_0 D3D11QUERY_STATS_STREAMOUTPUT_0
#define DEVICEQUERY_STATS_STREAMOUTPUT_1 D3D11QUERY_STATS_STREAMOUTPUT_1
#define DEVICEQUERY_STATS_STREAMOUTPUT_2 D3D11QUERY_STATS_STREAMOUTPUT_2
#define DEVICEQUERY_STATS_STREAMOUTPUT_3 D3D11QUERY_STATS_STREAMOUTPUT_3

typedef D3D11PredicateType                      DevicePredicateType;
#define DEVICEPREDICATE_OCCLUSION               D3D11PREDICATE_OCCLUSION
#define DEVICEPREDICATE_OVERFLOW_STREAMOUTPUT   D3D11PREDICATE_OVERFLOW_STREAMOUTPUT
#define DEVICEPREDICATE_OVERFLOW_STREAMOUTPUT_0 D3D11PREDICATE_OVERFLOW_STREAMOUTPUT_0
#define DEVICEPREDICATE_OVERFLOW_STREAMOUTPUT_1 D3D11PREDICATE_OVERFLOW_STREAMOUTPUT_1
#define DEVICEPREDICATE_OVERFLOW_STREAMOUTPUT_2 D3D11PREDICATE_OVERFLOW_STREAMOUTPUT_2
#define DEVICEPREDICATE_OVERFLOW_STREAMOUTPUT_3 D3D11PREDICATE_OVERFLOW_STREAMOUTPUT_3

typedef D3D11CounterType    DeviceCounterType;
#define DEVICECOUNTER_FLOAT D3D11COUNTER_FLOAT
#define DEVICECOUNTER_WORD  D3D11COUNTER_WORD
#define DEVICECOUNTER_DWORD D3D11COUNTER_DWORD
#define DEVICECOUNTER_QWORD D3D11COUNTER_QWORD

typedef D3D11CounterDesc DeviceCounterDesc;

typedef D3D11Asynchronous                  DeviceAsynchronous;
typedef D3D11Query                         DeviceQuery;
typedef D3D11QueryCommandProcessing        DeviceQueryCommandProcessing;
typedef D3D11QueryOcclusion                DeviceQueryOcclusion;
typedef D3D11QueryTimeStampFrequency       DeviceQueryTimeStampFrequency;
typedef D3D11QueryTimeStamp                DeviceQueryTimeStamp;
typedef D3D11QueryStatsPipeline            DeviceQueryStatsPipeline;
typedef D3D11QueryStatsStreamOutput        DeviceQueryStatsStreamOutput;
typedef D3D11Predicate                     DevicePredicate;
typedef D3D11PredicateOcclusion            DevicePredicateOcclusion;
typedef D3D11PredicateStreamOutputOverflow DevicePredicateStreamOutputOverflow;
typedef D3D11Counter                       DeviceCounter;

/////////////////////////////////////////////////////////////////////////////////
// DeviceResource Definitions
typedef D3D11ResourceType               DeviceResourceType;
#define DEVICERESOURCE_BUFFER_VERTEX   D3D11RESOURCE_BUFFER_VERTEX
#define DEVICERESOURCE_BUFFER_INDEX    D3D11RESOURCE_BUFFER_INDEX
#define DEVICERESOURCE_BUFFER_CONSTANT D3D11RESOURCE_BUFFER_CONSTANT
#define DEVICERESOURCE_BUFFER_RAW      D3D11RESOURCE_BUFFER_RAW
#define DEVICERESOURCE_BUFFER_STRUCT   D3D11RESOURCE_BUFFER_STRUCT
#define DEVICERESOURCE_TEXTURE_1D      D3D11RESOURCE_TEXTURE_1D
#define DEVICERESOURCE_TEXTURE_2D      D3D11RESOURCE_TEXTURE_2D
#define DEVICERESOURCE_TEXTURE_3D      D3D11RESOURCE_TEXTURE_3D
#define DEVICERESOURCE_TEXTURE_CUBE    D3D11RESOURCE_TEXTURE_CUBE

typedef D3D11ResourcePriority           DeviceResourcePriority;
#define DEVICERESOURCE_PRIORITY_MINIMUM D3D11RESOURCE_PRIORITY_MINIMUM
#define DEVICERESOURCE_PRIORITY_LOW     D3D11RESOURCE_PRIORITY_LOW
#define DEVICERESOURCE_PRIORITY_NORMAL  D3D11RESOURCE_PRIORITY_NORMAL
#define DEVICERESOURCE_PRIORITY_HIGH    D3D11RESOURCE_PRIORITY_HIGH
#define DEVICERESOURCE_PRIORITY_MAXIMUM D3D11RESOURCE_PRIORITY_MAXIMUM

typedef D3D11ResourceUsage           DeviceResourceUsage;
#define DEVICERESOURCE_USAGE_DEFAULT D3D11RESOURCE_USAGE_DEFAULT
#define DEVICERESOURCE_USAGE_CONST   D3D11RESOURCE_USAGE_CONST
#define DEVICERESOURCE_USAGE_DYNAMIC D3D11RESOURCE_USAGE_DYNAMIC
#define DEVICERESOURCE_USAGE_STAGING D3D11RESOURCE_USAGE_STAGING

typedef D3D11ResourceBind                    DeviceResourceBind;
#define DEVICERESOURCE_BIND_NONE             D3D11RESOURCE_BIND_NONE
#define DEVICERESOURCE_BIND_VERTEX_BUFFER    D3D11RESOURCE_BIND_VERTEX_BUFFER
#define DEVICERESOURCE_BIND_INDEX_BUFFER     D3D11RESOURCE_BIND_INDEX_BUFFER
#define DEVICERESOURCE_BIND_CONSTANT_BUFFER  D3D11RESOURCE_BIND_CONSTANT_BUFFER
#define DEVICERESOURCE_BIND_SHADER_INPUT     D3D11RESOURCE_BIND_SHADER_INPUT
#define DEVICERESOURCE_BIND_STREAM_OUTPUT    D3D11RESOURCE_BIND_STREAM_OUTPUT
#define DEVICERESOURCE_BIND_RENDER_TARGET    D3D11RESOURCE_BIND_RENDER_TARGET
#define DEVICERESOURCE_BIND_DEPTH_STENCIL    D3D11RESOURCE_BIND_DEPTH_STENCIL
#define DEVICERESOURCE_BIND_UNORDERED_ACCESS D3D11RESOURCE_BIND_UNORDERED_ACCESS

typedef D3D11ResourceDimension           DeviceResourceDimension;
#define DEVICERESOURCE_DIMENSION_UNKNOWN D3D11RESOURCE_DIMENSION_UNKNOWN
#define DEVICERESOURCE_DIMENSION_BUFFER  D3D11RESOURCE_DIMENSION_BUFFER
#define DEVICERESOURCE_DIMENSION_1D      D3D11RESOURCE_DIMENSION_1D
#define DEVICERESOURCE_DIMENSION_2D      D3D11RESOURCE_DIMENSION_2D
#define DEVICERESOURCE_DIMENSION_3D      D3D11RESOURCE_DIMENSION_3D

typedef D3D11ResourceLock                      DeviceResourceLock;
#define DEVICERESOURCE_LOCK_NONE               D3D11RESOURCE_LOCK_NONE
#define DEVICERESOURCE_LOCK_READ               D3D11RESOURCE_LOCK_READ
#define DEVICERESOURCE_LOCK_WRITE              D3D11RESOURCE_LOCK_WRITE
#define DEVICERESOURCE_LOCK_READ_WRITE         D3D11RESOURCE_LOCK_READ_WRITE
#define DEVICERESOURCE_LOCK_WRITE_DISCARD      D3D11RESOURCE_LOCK_WRITE_DISCARD
#define DEVICERESOURCE_LOCK_WRITE_NO_OVERWRITE D3D11RESOURCE_LOCK_WRITE_NO_OVERWRITE

typedef D3D11ResourceLockFlags            DeviceResourceLockFlags;
#define DEVICERESOURCE_LOCKFLAG_NONE      D3D11RESOURCE_LOCKFLAG_NONE
#define DEVICERESOURCE_LOCKFLAG_DONT_WAIT D3D11RESOURCE_LOCKFLAG_DONT_WAIT

typedef D3D11Resource DeviceResource;

/////////////////////////////////////////////////////////////////////////////////
// DeviceBuffer Definitions
#define DEVICECONSTANTBUFFER_REGISTER_SIZE            D3D11CONSTANTBUFFER_REGISTER_SIZE
#define DEVICECONSTANTBUFFER_REGISTER_COMPONENT_SIZE  D3D11CONSTANTBUFFER_REGISTER_COMPONENT_SIZE
#define DEVICECONSTANTBUFFER_REGISTER_COMPONENT_COUNT D3D11CONSTANTBUFFER_REGISTER_COMPONENT_COUNT

typedef D3D11Buffer           DeviceBuffer;
typedef D3D11VertexBuffer     DeviceVertexBuffer;
typedef D3D11IndexBuffer      DeviceIndexBuffer;
typedef D3D11ConstantBuffer   DeviceConstantBuffer;
typedef D3D11RawBuffer        DeviceRawBuffer;
typedef D3D11StructuredBuffer DeviceStructuredBuffer;

/////////////////////////////////////////////////////////////////////////////////
// DeviceTexture Definitions
#define DEVICETEXTURE_MAX_DIMENSIONS D3D11TEXTURE_MAX_DIMENSIONS
#define DEVICETEXTURE_MIPLEVELS_AUTO D3D11TEXTURE_MIPLEVELS_AUTO
#define DEVICETEXTURE_MIPLEVELS_NONE D3D11TEXTURE_MIPLEVELS_NONE

typedef D3D11SubResourceIndex  DeviceSubResourceIndex;
typedef D3D11SubResourceRegion DeviceSubResourceRegion;

typedef D3D11TextureCubeFace         DeviceTextureCubeFace;
#define DEVICETEXTURE_CUBEFACE_X_POS D3D11TEXTURE_CUBEFACE_X_POS
#define DEVICETEXTURE_CUBEFACE_X_NEG D3D11TEXTURE_CUBEFACE_X_NEG
#define DEVICETEXTURE_CUBEFACE_Y_POS D3D11TEXTURE_CUBEFACE_Y_POS
#define DEVICETEXTURE_CUBEFACE_Y_NEG D3D11TEXTURE_CUBEFACE_Y_NEG
#define DEVICETEXTURE_CUBEFACE_Z_POS D3D11TEXTURE_CUBEFACE_Z_POS
#define DEVICETEXTURE_CUBEFACE_Z_NEG D3D11TEXTURE_CUBEFACE_Z_NEG

typedef D3D11Texture     DeviceTexture;
typedef D3D11Texture1D   DeviceTexture1D;
typedef D3D11Texture2D   DeviceTexture2D;
typedef D3D11Texture3D   DeviceTexture3D;
typedef D3D11TextureCube DeviceTextureCube;

/////////////////////////////////////////////////////////////////////////////////
// DeviceResourceView Definitions
typedef D3D11ResourceViewType                DeviceResourceViewType;
#define DEVICERESOURCEVIEW_RENDER_TARGET    D3D11RESOURCEVIEW_RENDER_TARGET
#define DEVICERESOURCEVIEW_DEPTH_STENCIL    D3D11RESOURCEVIEW_DEPTH_STENCIL
#define DEVICERESOURCEVIEW_SHADER           D3D11RESOURCEVIEW_SHADER
#define DEVICERESOURCEVIEW_UNORDERED_ACCESS D3D11RESOURCEVIEW_UNORDERED_ACCESS

typedef D3D11RenderTargetViewDimension              DeviceRenderTargetViewDimension;
#define DEVICERENDERTARGETVIEW_DIM_UNKNOWN          D3D11RENDERTARGETVIEW_DIM_UNKNOWN
#define DEVICERENDERTARGETVIEW_DIM_BUFFER           D3D11RENDERTARGETVIEW_DIM_BUFFER
#define DEVICERENDERTARGETVIEW_DIM_TEXTURE1D        D3D11RENDERTARGETVIEW_DIM_TEXTURE1D
#define DEVICERENDERTARGETVIEW_DIM_TEXTURE1DARRAY   D3D11RENDERTARGETVIEW_DIM_TEXTURE1DARRAY
#define DEVICERENDERTARGETVIEW_DIM_TEXTURE2D        D3D11RENDERTARGETVIEW_DIM_TEXTURE2D
#define DEVICERENDERTARGETVIEW_DIM_TEXTURE2DARRAY   D3D11RENDERTARGETVIEW_DIM_TEXTURE2DARRAY
#define DEVICERENDERTARGETVIEW_DIM_TEXTURE2DMS      D3D11RENDERTARGETVIEW_DIM_TEXTURE2DMS
#define DEVICERENDERTARGETVIEW_DIM_TEXTURE2DMSARRAY D3D11RENDERTARGETVIEW_DIM_TEXTURE2DMSARRAY
#define DEVICERENDERTARGETVIEW_DIM_TEXTURE3D        D3D11RENDERTARGETVIEW_DIM_TEXTURE3D

typedef D3D11RenderTargetViewDesc DeviceRenderTargetViewDesc;

typedef D3D11DepthStencilViewDimension              DeviceDepthStencilViewDimension;
#define DEVICEDEPTHSTENCILVIEW_DIM_UNKNOWN          D3D11DEPTHSTENCILVIEW_DIM_UNKNOWN
#define DEVICEDEPTHSTENCILVIEW_DIM_TEXTURE1D        D3D11DEPTHSTENCILVIEW_DIM_TEXTURE1D
#define DEVICEDEPTHSTENCILVIEW_DIM_TEXTURE1DARRAY   D3D11DEPTHSTENCILVIEW_DIM_TEXTURE1DARRAY
#define DEVICEDEPTHSTENCILVIEW_DIM_TEXTURE2D        D3D11DEPTHSTENCILVIEW_DIM_TEXTURE2D
#define DEVICEDEPTHSTENCILVIEW_DIM_TEXTURE2DARRAY   D3D11DEPTHSTENCILVIEW_DIM_TEXTURE2DARRAY
#define DEVICEDEPTHSTENCILVIEW_DIM_TEXTURE2DMS      D3D11DEPTHSTENCILVIEW_DIM_TEXTURE2DMS
#define DEVICEDEPTHSTENCILVIEW_DIM_TEXTURE2DMSARRAY D3D11DEPTHSTENCILVIEW_DIM_TEXTURE2DMSARRAY

typedef D3D11DepthStencilViewFlags                   DeviceDepthStencilViewFlags;
#define DEVICEDEPTHSTENCILVIEW_FLAG_NONE             D3D11DEPTHSTENCILVIEW_FLAG_NONE
#define DEVICEDEPTHSTENCILVIEW_FLAG_READONLY_DEPTH   D3D11DEPTHSTENCILVIEW_FLAG_READONLY_DEPTH
#define DEVICEDEPTHSTENCILVIEW_FLAG_READONLY_STENCIL D3D11DEPTHSTENCILVIEW_FLAG_READONLY_STENCIL

typedef D3D11DepthStencilViewDesc DeviceDepthStencilViewDesc;

typedef D3D11ShaderViewDimension              DeviceShaderViewDimension;
#define DEVICESHADERVIEW_DIM_UNKNOWN          D3D11SHADERVIEW_DIM_UNKNOWN
#define DEVICESHADERVIEW_DIM_BUFFER           D3D11SHADERVIEW_DIM_BUFFER
#define DEVICESHADERVIEW_DIM_BUFFEREX         D3D11SHADERVIEW_DIM_BUFFEREX
#define DEVICESHADERVIEW_DIM_TEXTURE1D        D3D11SHADERVIEW_DIM_TEXTURE1D
#define DEVICESHADERVIEW_DIM_TEXTURE1DARRAY   D3D11SHADERVIEW_DIM_TEXTURE1DARRAY
#define DEVICESHADERVIEW_DIM_TEXTURE2D        D3D11SHADERVIEW_DIM_TEXTURE2D
#define DEVICESHADERVIEW_DIM_TEXTURE2DARRAY   D3D11SHADERVIEW_DIM_TEXTURE2DARRAY
#define DEVICESHADERVIEW_DIM_TEXTURE2DMS      D3D11SHADERVIEW_DIM_TEXTURE2DMS
#define DEVICESHADERVIEW_DIM_TEXTURE2DMSARRAY D3D11SHADERVIEW_DIM_TEXTURE2DMSARRAY
#define DEVICESHADERVIEW_DIM_TEXTURE3D        D3D11SHADERVIEW_DIM_TEXTURE3D
#define DEVICESHADERVIEW_DIM_TEXTURECUBE      D3D11SHADERVIEW_DIM_TEXTURECUBE
#define DEVICESHADERVIEW_DIM_TEXTURECUBEARRAY D3D11SHADERVIEW_DIM_TEXTURECUBEARRAY

typedef D3D11ShaderViewBufferExFlags       DeviceShaderViewBufferExFlags;
#define DEVICESHADERVIEW_BUFFEREXFLAG_NONE D3D11SHADERVIEW_BUFFEREXFLAG_NONE
#define DEVICESHADERVIEW_BUFFEREXFLAG_RAW  D3D11SHADERVIEW_BUFFEREXFLAG_RAW

typedef D3D11ShaderViewDesc DeviceShaderViewDesc;

typedef D3D11UnorderedAccessViewDimension            DeviceUnorderedAccessViewDimension;
#define DEVICEUNORDEREDACCESSVIEW_DIM_UNKNOWN        D3D11UNORDEREDACCESSVIEW_DIM_UNKNOWN
#define DEVICEUNORDEREDACCESSVIEW_DIM_BUFFER         D3D11UNORDEREDACCESSVIEW_DIM_BUFFER
#define DEVICEUNORDEREDACCESSVIEW_DIM_TEXTURE1D      D3D11UNORDEREDACCESSVIEW_DIM_TEXTURE1D
#define DEVICEUNORDEREDACCESSVIEW_DIM_TEXTURE1DARRAY D3D11UNORDEREDACCESSVIEW_DIM_TEXTURE1DARRAY
#define DEVICEUNORDEREDACCESSVIEW_DIM_TEXTURE2D      D3D11UNORDEREDACCESSVIEW_DIM_TEXTURE2D
#define DEVICEUNORDEREDACCESSVIEW_DIM_TEXTURE2DARRAY D3D11UNORDEREDACCESSVIEW_DIM_TEXTURE2DARRAY
#define DEVICEUNORDEREDACCESSVIEW_DIM_TEXTURE3D      D3D11UNORDEREDACCESSVIEW_DIM_TEXTURE3D

typedef D3D11UnorderedAccessViewBufferFlags          DeviceUnorderedAccessViewBufferFlags;
#define DEVICEUNORDEREDACCESSVIEW_BUFFERFLAG_NONE    D3D11UNORDEREDACCESSVIEW_BUFFERFLAG_NONE
#define DEVICEUNORDEREDACCESSVIEW_BUFFERFLAG_RAW     D3D11UNORDEREDACCESSVIEW_BUFFERFLAG_RAW
#define DEVICEUNORDEREDACCESSVIEW_BUFFERFLAG_APPEND  D3D11UNORDEREDACCESSVIEW_BUFFERFLAG_APPEND
#define DEVICEUNORDEREDACCESSVIEW_BUFFERFLAG_COUNTER D3D11UNORDEREDACCESSVIEW_BUFFERFLAG_COUNTER

typedef D3D11UnorderedAccessViewDesc DeviceUnorderedAccessViewDesc;

typedef D3D11ResourceView        DeviceResourceView;
typedef D3D11RenderTargetView    DeviceRenderTargetView;
typedef D3D11DepthStencilView    DeviceDepthStencilView;
typedef D3D11ShaderView          DeviceShaderView;
typedef D3D11UnorderedAccessView DeviceUnorderedAccessView;

/////////////////////////////////////////////////////////////////////////////////
// DeviceShader Definitions
typedef D3D11ShaderType        DeviceShaderType;
#define DEVICESHADER_VERTEX   D3D11SHADER_VERTEX
#define DEVICESHADER_GEOMETRY D3D11SHADER_GEOMETRY
#define DEVICESHADER_PIXEL    D3D11SHADER_PIXEL
#define DEVICESHADER_HULL     D3D11SHADER_HULL
#define DEVICESHADER_DOMAIN   D3D11SHADER_DOMAIN
#define DEVICESHADER_COMPUTE  D3D11SHADER_COMPUTE

typedef D3D11ShaderCompilationData DeviceShaderCompilationData;

typedef D3D11StreamOutputDeclaration DeviceStreamOutputDeclaration;

typedef D3D11ShaderCompilationFlags                   DeviceShaderCompilationFlags;
#define DEVICESHADER_COMPILE_NONE                     D3D11SHADER_COMPILE_NONE
#define DEVICESHADER_COMPILE_DEBUG                    D3D11SHADER_COMPILE_DEBUG
#define DEVICESHADER_COMPILE_WARNINGS_AS_ERRORS       D3D11SHADER_COMPILE_WARNINGS_AS_ERRORS
#define DEVICESHADER_COMPILE_STRICT                   D3D11SHADER_COMPILE_STRICT
#define DEVICESHADER_COMPILE_STRICT_IEEE              D3D11SHADER_COMPILE_STRICT_IEEE
#define DEVICESHADER_COMPILE_BACKWARDS_COMPATIBILITY  D3D11SHADER_COMPILE_BACKWARDS_COMPATIBILITY
#define DEVICESHADER_COMPILE_SKIP_OPTIMIZATION        D3D11SHADER_COMPILE_SKIP_OPTIMIZATION
#define DEVICESHADER_COMPILE_SKIP_VALIDATION          D3D11SHADER_COMPILE_SKIP_VALIDATION
#define DEVICESHADER_COMPILE_VS_SOFTWARE_NO_OPT       D3D11SHADER_COMPILE_VS_SOFTWARE_NO_OPT
#define DEVICESHADER_COMPILE_PS_SOFTWARE_NO_OPT       D3D11SHADER_COMPILE_PS_SOFTWARE_NO_OPT
#define DEVICESHADER_COMPILE_NO_PRESHADER             D3D11SHADER_COMPILE_NO_PRESHADER
#define DEVICESHADER_COMPILE_PARTIAL_PRECISION        D3D11SHADER_COMPILE_PARTIAL_PRECISION
#define DEVICESHADER_COMPILE_PACK_MATRIX_ROW_MAJOR    D3D11SHADER_COMPILE_PACK_MATRIX_ROW_MAJOR
#define DEVICESHADER_COMPILE_PACK_MATRIX_COLUMN_MAJOR D3D11SHADER_COMPILE_PACK_MATRIX_COLUMN_MAJOR
#define DEVICESHADER_COMPILE_AVOID_FLOW_CONTROL       D3D11SHADER_COMPILE_AVOID_FLOW_CONTROL
#define DEVICESHADER_COMPILE_PREFER_FLOW_CONTROL      D3D11SHADER_COMPILE_PREFER_FLOW_CONTROL
#define DEVICESHADER_COMPILE_OPTIMIZATION_LEVEL0      D3D11SHADER_COMPILE_OPTIMIZATION_LEVEL0
#define DEVICESHADER_COMPILE_OPTIMIZATION_LEVEL1      D3D11SHADER_COMPILE_OPTIMIZATION_LEVEL1
#define DEVICESHADER_COMPILE_OPTIMIZATION_LEVEL2      D3D11SHADER_COMPILE_OPTIMIZATION_LEVEL2
#define DEVICESHADER_COMPILE_OPTIMIZATION_LEVEL3      D3D11SHADER_COMPILE_OPTIMIZATION_LEVEL3

typedef D3D11ShaderRequirementFlags                  DeviceShaderRequirementFlags;
#define DEVICESHADER_REQUIRES_NONE                   D3D11SHADER_REQUIRES_NONE
#define DEVICESHADER_REQUIRES_9_X_SHADOWS            D3D11SHADER_REQUIRES_9_X_SHADOWS
#define DEVICESHADER_REQUIRES_11_1_DOUBLE_EXTENSIONS D3D11SHADER_REQUIRES_11_1_DOUBLE_EXTENSIONS
#define DEVICESHADER_REQUIRES_11_1_SHADER_EXTENSIONS D3D11SHADER_REQUIRES_11_1_SHADER_EXTENSIONS
#define DEVICESHADER_REQUIRES_DOUBLES                D3D11SHADER_REQUIRES_DOUBLES
#define DEVICESHADER_REQUIRES_MINIMUM_PRECISION      D3D11SHADER_REQUIRES_MINIMUM_PRECISION
#define DEVICESHADER_REQUIRES_EARLY_DEPTH_STENCIL    D3D11SHADER_REQUIRES_EARLY_DEPTH_STENCIL
#define DEVICESHADER_REQUIRES_UAVS_64                D3D11SHADER_REQUIRES_UAVS_64
#define DEVICESHADER_REQUIRES_UAVS_AT_EVERY_STAGE    D3D11SHADER_REQUIRES_UAVS_AT_EVERY_STAGE

typedef D3D11ShaderPrimitive                          DeviceShaderPrimitive;
#define DEVICESHADER_PRIMITIVE_UNDEFINED              D3D11SHADER_PRIMITIVE_UNDEFINED
#define DEVICESHADER_PRIMITIVE_POINT                  D3D11SHADER_PRIMITIVE_POINT
#define DEVICESHADER_PRIMITIVE_LINE                   D3D11SHADER_PRIMITIVE_LINE
#define DEVICESHADER_PRIMITIVE_TRIANGLE               D3D11SHADER_PRIMITIVE_TRIANGLE
#define DEVICESHADER_PRIMITIVE_LINE_ADJ               D3D11SHADER_PRIMITIVE_LINE_ADJ
#define DEVICESHADER_PRIMITIVE_TRIANGLE_ADJ           D3D11SHADER_PRIMITIVE_TRIANGLE_ADJ
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_1  D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_1
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_2  D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_2
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_3  D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_3
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_4  D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_4
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_5  D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_5
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_6  D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_6
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_7  D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_7
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_8  D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_8
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_9  D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_9
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_10 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_10
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_11 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_11
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_12 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_12
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_13 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_13
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_14 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_14
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_15 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_15
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_16 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_16
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_17 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_17
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_18 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_18
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_19 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_19
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_20 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_20
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_21 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_21
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_22 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_22
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_23 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_23
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_24 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_24
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_25 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_25
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_26 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_26
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_27 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_27
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_28 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_28
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_29 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_29
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_30 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_30
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_31 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_31
#define DEVICESHADER_PRIMITIVE_CONTROL_POINT_PATCH_32 D3D11SHADER_PRIMITIVE_CONTROL_POINT_PATCH_32

typedef D3D11ShaderPrimitiveTopology                              DeviceShaderPrimitiveTopology;
#define DEVICESHADER_PRIMITIVETOPOLOGY_UNDEFINED                  D3D11SHADER_PRIMITIVETOPOLOGY_UNDEFINED
#define DEVICESHADER_PRIMITIVETOPOLOGY_POINTLIST                  D3D11SHADER_PRIMITIVETOPOLOGY_POINTLIST
#define DEVICESHADER_PRIMITIVETOPOLOGY_LINELIST                   D3D11SHADER_PRIMITIVETOPOLOGY_LINELIST
#define DEVICESHADER_PRIMITIVETOPOLOGY_LINESTRIP                  D3D11SHADER_PRIMITIVETOPOLOGY_LINESTRIP
#define DEVICESHADER_PRIMITIVETOPOLOGY_TRIANGLELIST               D3D11SHADER_PRIMITIVETOPOLOGY_TRIANGLELIST
#define DEVICESHADER_PRIMITIVETOPOLOGY_TRIANGLESTRIP              D3D11SHADER_PRIMITIVETOPOLOGY_TRIANGLESTRIP
#define DEVICESHADER_PRIMITIVETOPOLOGY_LINELIST_ADJ               D3D11SHADER_PRIMITIVETOPOLOGY_LINELIST_ADJ
#define DEVICESHADER_PRIMITIVETOPOLOGY_LINESTRIP_ADJ              D3D11SHADER_PRIMITIVETOPOLOGY_LINESTRIP_ADJ
#define DEVICESHADER_PRIMITIVETOPOLOGY_TRIANGLELIST_ADJ           D3D11SHADER_PRIMITIVETOPOLOGY_TRIANGLELIST_ADJ
#define DEVICESHADER_PRIMITIVETOPOLOGY_TRIANGLESTRIP_ADJ          D3D11SHADER_PRIMITIVETOPOLOGY_TRIANGLESTRIP_ADJ
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_1  D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_1
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_2  D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_2
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_3  D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_3
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_4  D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_4
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_5  D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_5
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_6  D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_6
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_7  D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_7
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_8  D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_8
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_9  D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_9
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_10 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_10
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_11 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_11
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_12 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_12
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_13 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_13
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_14 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_14
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_15 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_15
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_16 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_16
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_17 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_17
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_18 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_18
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_19 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_19
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_20 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_20
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_21 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_21
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_22 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_22
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_23 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_23
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_24 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_24
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_25 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_25
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_26 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_26
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_27 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_27
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_28 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_28
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_29 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_29
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_30 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_30
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_31 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_31
#define DEVICESHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_32 D3D11SHADER_PRIMITIVETOPOLOGY_CONTROL_POINT_PATCHLIST_32

typedef D3D11ShaderTesselatorOutput                 DeviceShaderTesselatorOutput;
#define DEVICESHADER_TESSELLATOROUTPUT_UNDEFINED    D3D11SHADER_TESSELLATOROUTPUT_UNDEFINED
#define DEVICESHADER_TESSELLATOROUTPUT_POINT        D3D11SHADER_TESSELLATOROUTPUT_POINT
#define DEVICESHADER_TESSELLATOROUTPUT_LINE         D3D11SHADER_TESSELLATOROUTPUT_LINE
#define DEVICESHADER_TESSELLATOROUTPUT_TRIANGLE_CW  D3D11SHADER_TESSELLATOROUTPUT_TRIANGLE_CW
#define DEVICESHADER_TESSELLATOROUTPUT_TRIANGLE_CCW D3D11SHADER_TESSELLATOROUTPUT_TRIANGLE_CCW

typedef D3D11ShaderTesselatorPartitioning                    DeviceShaderTesselatorPartitioning;
#define DEVICESHADER_TESSELLATORPARTITIONING_UNDEFINED       D3D11SHADER_TESSELLATORPARTITIONING_UNDEFINED
#define DEVICESHADER_TESSELLATORPARTITIONING_INTEGER         D3D11SHADER_TESSELLATORPARTITIONING_INTEGER
#define DEVICESHADER_TESSELLATORPARTITIONING_POW2            D3D11SHADER_TESSELLATORPARTITIONING_POW2
#define DEVICESHADER_TESSELLATORPARTITIONING_FRACTIONAL_ODD  D3D11SHADER_TESSELLATORPARTITIONING_FRACTIONAL_ODD
#define DEVICESHADER_TESSELLATORPARTITIONING_FRACTIONAL_EVEN D3D11SHADER_TESSELLATORPARTITIONING_FRACTIONAL_EVEN

typedef D3D11ShaderTesselatorDomain              DeviceShaderTesselatorDomain;
#define DEVICESHADER_TESSELLATORDOMAIN_UNDEFINED D3D11SHADER_TESSELLATORDOMAIN_UNDEFINED
#define DEVICESHADER_TESSELLATORDOMAIN_ISOLINE   D3D11SHADER_TESSELLATORDOMAIN_ISOLINE
#define DEVICESHADER_TESSELLATORDOMAIN_TRIANGLE  D3D11SHADER_TESSELLATORDOMAIN_TRIANGLE
#define DEVICESHADER_TESSELLATORDOMAIN_QUAD      D3D11SHADER_TESSELLATORDOMAIN_QUAD

typedef D3D11ShaderDesc DeviceShaderDesc;

typedef D3D11ShaderParameterType                             DeviceShaderParameterType;
#define DEVICESHADER_PARAMETER_UNDEFINED                     D3D11SHADER_PARAMETER_UNDEFINED
#define DEVICESHADER_PARAMETER_VERTEX_ID                     D3D11SHADER_PARAMETER_VERTEX_ID
#define DEVICESHADER_PARAMETER_PRIMITIVE_ID                  D3D11SHADER_PARAMETER_PRIMITIVE_ID
#define DEVICESHADER_PARAMETER_INSTANCE_ID                   D3D11SHADER_PARAMETER_INSTANCE_ID
#define DEVICESHADER_PARAMETER_POSITION                      D3D11SHADER_PARAMETER_POSITION
#define DEVICESHADER_PARAMETER_CLIP_DISTANCE                 D3D11SHADER_PARAMETER_CLIP_DISTANCE
#define DEVICESHADER_PARAMETER_CULL_DISTANCE                 D3D11SHADER_PARAMETER_CULL_DISTANCE
#define DEVICESHADER_PARAMETER_IS_FRONT_FACE                 D3D11SHADER_PARAMETER_IS_FRONT_FACE
#define DEVICESHADER_PARAMETER_SAMPLE_INDEX                  D3D11SHADER_PARAMETER_SAMPLE_INDEX
#define DEVICESHADER_PARAMETER_TARGET                        D3D11SHADER_PARAMETER_TARGET
#define DEVICESHADER_PARAMETER_RENDER_TARGET_ARRAY_INDEX     D3D11SHADER_PARAMETER_RENDER_TARGET_ARRAY_INDEX
#define DEVICESHADER_PARAMETER_VIEWPORT_ARRAY_INDEX          D3D11SHADER_PARAMETER_VIEWPORT_ARRAY_INDEX
#define DEVICESHADER_PARAMETER_DEPTH                         D3D11SHADER_PARAMETER_DEPTH
#define DEVICESHADER_PARAMETER_DEPTH_GREATER_EQUAL           D3D11SHADER_PARAMETER_DEPTH_GREATER_EQUAL
#define DEVICESHADER_PARAMETER_DEPTH_LESS_EQUAL              D3D11SHADER_PARAMETER_DEPTH_LESS_EQUAL
#define DEVICESHADER_PARAMETER_COVERAGE                      D3D11SHADER_PARAMETER_COVERAGE
#define DEVICESHADER_PARAMETER_TESSFACTOR_FINAL_LINE_DETAIL  D3D11SHADER_PARAMETER_TESSFACTOR_FINAL_LINE_DETAIL
#define DEVICESHADER_PARAMETER_TESSFACTOR_FINAL_LINE_DENSITY D3D11SHADER_PARAMETER_TESSFACTOR_FINAL_LINE_DENSITY
#define DEVICESHADER_PARAMETER_TESSFACTOR_FINAL_TRI_EDGE     D3D11SHADER_PARAMETER_TESSFACTOR_FINAL_TRI_EDGE
#define DEVICESHADER_PARAMETER_TESSFACTOR_FINAL_TRI_INSIDE   D3D11SHADER_PARAMETER_TESSFACTOR_FINAL_TRI_INSIDE
#define DEVICESHADER_PARAMETER_TESSFACTOR_FINAL_QUAD_EDGE    D3D11SHADER_PARAMETER_TESSFACTOR_FINAL_QUAD_EDGE
#define DEVICESHADER_PARAMETER_TESSFACTOR_FINAL_QUAD_INSIDE  D3D11SHADER_PARAMETER_TESSFACTOR_FINAL_QUAD_INSIDE

typedef D3D11ShaderRegisterComponentType       DeviceShaderRegisterComponentType;
#define DEVICESHADER_REGISTERCOMPONENT_UNKNOWN D3D11SHADER_REGISTERCOMPONENT_UNKNOWN
#define DEVICESHADER_REGISTERCOMPONENT_FLOAT32 D3D11SHADER_REGISTERCOMPONENT_FLOAT32
#define DEVICESHADER_REGISTERCOMPONENT_UINT32  D3D11SHADER_REGISTERCOMPONENT_UINT32
#define DEVICESHADER_REGISTERCOMPONENT_SINT32  D3D11SHADER_REGISTERCOMPONENT_SINT32

typedef D3D11ShaderMinPrecision             DeviceShaderMinPrecision;
#define DEVICESHADER_MINPRECISION_FLOAT_32  D3D11SHADER_MINPRECISION_FLOAT_32
#define DEVICESHADER_MINPRECISION_FLOAT_16  D3D11SHADER_MINPRECISION_FLOAT_16
#define DEVICESHADER_MINPRECISION_FLOAT_2_8 D3D11SHADER_MINPRECISION_FLOAT_2_8
#define DEVICESHADER_MINPRECISION_UINT_16   D3D11SHADER_MINPRECISION_UINT_16
#define DEVICESHADER_MINPRECISION_SINT_16   D3D11SHADER_MINPRECISION_SINT_16
#define DEVICESHADER_MINPRECISION_ANY_16    D3D11SHADER_MINPRECISION_ANY_16
#define DEVICESHADER_MINPRECISION_ANY_10    D3D11SHADER_MINPRECISION_ANY_10

typedef D3D11ShaderParameterDesc DeviceShaderParameterDesc;

typedef D3D11ShaderInputType                             DeviceShaderInputType;
#define DEVICESHADER_INPUT_CBUFFER                       D3D11SHADER_INPUT_CBUFFER
#define DEVICESHADER_INPUT_TBUFFER                       D3D11SHADER_INPUT_TBUFFER
#define DEVICESHADER_INPUT_TEXTURE                       D3D11SHADER_INPUT_TEXTURE
#define DEVICESHADER_INPUT_SAMPLER                       D3D11SHADER_INPUT_SAMPLER
#define DEVICESHADER_INPUT_BYTEADDRESS                   D3D11SHADER_INPUT_BYTEADDRESS
#define DEVICESHADER_INPUT_STRUCTURED                    D3D11SHADER_INPUT_STRUCTURED
#define DEVICESHADER_INPUT_UAV_RWBYTEADDRESS             D3D11SHADER_INPUT_UAV_RWBYTEADDRESS
#define DEVICESHADER_INPUT_UAV_RWSTRUCTURED              D3D11SHADER_INPUT_UAV_RWSTRUCTURED
#define DEVICESHADER_INPUT_UAV_RWSTRUCTURED_APPEND       D3D11SHADER_INPUT_UAV_RWSTRUCTURED_APPEND
#define DEVICESHADER_INPUT_UAV_RWSTRUCTURED_CONSUME      D3D11SHADER_INPUT_UAV_RWSTRUCTURED_CONSUME
#define DEVICESHADER_INPUT_UAV_RWSTRUCTURED_WITH_COUNTER D3D11SHADER_INPUT_UAV_RWSTRUCTURED_WITH_COUNTER
#define DEVICESHADER_INPUT_UAV_RWTYPED                   D3D11SHADER_INPUT_UAV_RWTYPED

typedef D3D11ShaderInputFlags                      DeviceShaderInputFlags;
#define DEVICESHADER_INPUTFLAG_NONE                D3D11SHADER_INPUTFLAG_NONE
#define DEVICESHADER_INPUTFLAG_USERPACKED          D3D11SHADER_INPUTFLAG_USERPACKED
#define DEVICESHADER_INPUTFLAG_COMPARISON_SAMPLER  D3D11SHADER_INPUTFLAG_COMPARISON_SAMPLER
#define DEVICESHADER_INPUTFLAG_TEXTURE_COMPONENT_0 D3D11SHADER_INPUTFLAG_TEXTURE_COMPONENT_0
#define DEVICESHADER_INPUTFLAG_TEXTURE_COMPONENT_1 D3D11SHADER_INPUTFLAG_TEXTURE_COMPONENT_1
#define DEVICESHADER_INPUTFLAG_UNUSED              D3D11SHADER_INPUTFLAG_UNUSED
#define DEVICESHADER_INPUTFLAG_TEXTURE_COMPONENTS  D3D11SHADER_INPUTFLAG_TEXTURE_COMPONENTS

typedef D3D11ShaderReturnType         DeviceShaderReturnType;
#define DEVICESHADER_RETURN_UNORM     D3D11SHADER_RETURN_UNORM
#define DEVICESHADER_RETURN_SNORM     D3D11SHADER_RETURN_SNORM
#define DEVICESHADER_RETURN_UINT      D3D11SHADER_RETURN_UINT
#define DEVICESHADER_RETURN_SINT      D3D11SHADER_RETURN_SINT
#define DEVICESHADER_RETURN_FLOAT     D3D11SHADER_RETURN_FLOAT
#define DEVICESHADER_RETURN_DOUBLE    D3D11SHADER_RETURN_DOUBLE
#define DEVICESHADER_RETURN_MIXED     D3D11SHADER_RETURN_MIXED
#define DEVICESHADER_RETURN_CONTINUED D3D11SHADER_RETURN_CONTINUED

typedef D3D11ShaderBindingDesc DeviceShaderBindingDesc;

typedef D3D11ShaderConstantBufferType                  DeviceShaderConstantBufferType;
#define DEVICESHADER_CONSTANTBUFFER_CBUFFER            D3D11SHADER_CONSTANTBUFFER_CBUFFER
#define DEVICESHADER_CONSTANTBUFFER_TBUFFER            D3D11SHADER_CONSTANTBUFFER_TBUFFER
#define DEVICESHADER_CONSTANTBUFFER_INTERFACE_POINTERS D3D11SHADER_CONSTANTBUFFER_INTERFACE_POINTERS
#define DEVICESHADER_CONSTANTBUFFER_RESOURCE_BIND_INFO D3D11SHADER_CONSTANTBUFFER_RESOURCE_BIND_INFO

typedef D3D11ShaderConstantBufferFlags             DeviceShaderConstantBufferFlags;
#define DEVICESHADER_CONSTANTBUFFERFLAG_NONE       D3D11SHADER_CONSTANTBUFFERFLAG_NONE
#define DEVICESHADER_CONSTANTBUFFERFLAG_USERPACKED D3D11SHADER_CONSTANTBUFFERFLAG_USERPACKED

typedef D3D11ShaderConstantBufferDesc DeviceShaderConstantBufferDesc;

typedef D3D11ShaderVariableClass                     DeviceShaderVariableClass;
#define DEVICESHADER_VARIABLECLASS_SCALAR            D3D11SHADER_VARIABLECLASS_SCALAR
#define DEVICESHADER_VARIABLECLASS_VECTOR            D3D11SHADER_VARIABLECLASS_VECTOR
#define DEVICESHADER_VARIABLECLASS_MATRIX_ROWS       D3D11SHADER_VARIABLECLASS_MATRIX_ROWS
#define DEVICESHADER_VARIABLECLASS_MATRIX_COLUMNS    D3D11SHADER_VARIABLECLASS_MATRIX_COLUMNS
#define DEVICESHADER_VARIABLECLASS_STRUCT            D3D11SHADER_VARIABLECLASS_STRUCT
#define DEVICESHADER_VARIABLECLASS_OBJECT            D3D11SHADER_VARIABLECLASS_OBJECT
#define DEVICESHADER_VARIABLECLASS_INTERFACE_CLASS   D3D11SHADER_VARIABLECLASS_INTERFACE_CLASS
#define DEVICESHADER_VARIABLECLASS_INTERFACE_POINTER D3D11SHADER_VARIABLECLASS_INTERFACE_POINTER

typedef D3D11ShaderVariableType                        DeviceShaderVariableType;
#define DEVICESHADER_VARIABLE_VOID                     D3D11SHADER_VARIABLE_VOID
#define DEVICESHADER_VARIABLE_BOOL                     D3D11SHADER_VARIABLE_BOOL
#define DEVICESHADER_VARIABLE_BYTE                     D3D11SHADER_VARIABLE_BYTE
#define DEVICESHADER_VARIABLE_SHORT                    D3D11SHADER_VARIABLE_SHORT
#define DEVICESHADER_VARIABLE_USHORT                   D3D11SHADER_VARIABLE_USHORT
#define DEVICESHADER_VARIABLE_INT                      D3D11SHADER_VARIABLE_INT
#define DEVICESHADER_VARIABLE_UINT                     D3D11SHADER_VARIABLE_UINT
#define DEVICESHADER_VARIABLE_FLOAT                    D3D11SHADER_VARIABLE_FLOAT
#define DEVICESHADER_VARIABLE_DOUBLE                   D3D11SHADER_VARIABLE_DOUBLE
#define DEVICESHADER_VARIABLE_INT12                    D3D11SHADER_VARIABLE_INT12
#define DEVICESHADER_VARIABLE_FLOAT8                   D3D11SHADER_VARIABLE_FLOAT8
#define DEVICESHADER_VARIABLE_FLOAT10                  D3D11SHADER_VARIABLE_FLOAT10
#define DEVICESHADER_VARIABLE_FLOAT16                  D3D11SHADER_VARIABLE_FLOAT16
#define DEVICESHADER_VARIABLE_INTERFACEPOINTER         D3D11SHADER_VARIABLE_INTERFACEPOINTER
#define DEVICESHADER_VARIABLE_STRING                   D3D11SHADER_VARIABLE_STRING
#define DEVICESHADER_VARIABLE_BUFFER                   D3D11SHADER_VARIABLE_BUFFER
#define DEVICESHADER_VARIABLE_RWBUFFER                 D3D11SHADER_VARIABLE_RWBUFFER
#define DEVICESHADER_VARIABLE_CBUFFER                  D3D11SHADER_VARIABLE_CBUFFER
#define DEVICESHADER_VARIABLE_TBUFFER                  D3D11SHADER_VARIABLE_TBUFFER
#define DEVICESHADER_VARIABLE_RAWBUFFER                D3D11SHADER_VARIABLE_RAWBUFFER
#define DEVICESHADER_VARIABLE_RWRAWBUFFER              D3D11SHADER_VARIABLE_RWRAWBUFFER
#define DEVICESHADER_VARIABLE_STRUCTUREDBUFFER         D3D11SHADER_VARIABLE_STRUCTUREDBUFFER
#define DEVICESHADER_VARIABLE_RWSTRUCTUREDBUFFER       D3D11SHADER_VARIABLE_RWSTRUCTUREDBUFFER
#define DEVICESHADER_VARIABLE_STRUCTUREDBUFFER_APPEND  D3D11SHADER_VARIABLE_STRUCTUREDBUFFER_APPEND
#define DEVICESHADER_VARIABLE_STRUCTUREDBUFFER_CONSUME D3D11SHADER_VARIABLE_STRUCTUREDBUFFER_CONSUME
#define DEVICESHADER_VARIABLE_TEXTURE                  D3D11SHADER_VARIABLE_TEXTURE
#define DEVICESHADER_VARIABLE_TEXTURE1D                D3D11SHADER_VARIABLE_TEXTURE1D
#define DEVICESHADER_VARIABLE_TEXTURE1DARRAY           D3D11SHADER_VARIABLE_TEXTURE1DARRAY
#define DEVICESHADER_VARIABLE_RWTEXTURE1D              D3D11SHADER_VARIABLE_RWTEXTURE1D
#define DEVICESHADER_VARIABLE_RWTEXTURE1DARRAY         D3D11SHADER_VARIABLE_RWTEXTURE1DARRAY
#define DEVICESHADER_VARIABLE_TEXTURE2D                D3D11SHADER_VARIABLE_TEXTURE2D
#define DEVICESHADER_VARIABLE_TEXTURE2DARRAY           D3D11SHADER_VARIABLE_TEXTURE2DARRAY
#define DEVICESHADER_VARIABLE_RWTEXTURE2D              D3D11SHADER_VARIABLE_RWTEXTURE2D
#define DEVICESHADER_VARIABLE_RWTEXTURE2DARRAY         D3D11SHADER_VARIABLE_RWTEXTURE2DARRAY
#define DEVICESHADER_VARIABLE_TEXTURE2DMS              D3D11SHADER_VARIABLE_TEXTURE2DMS
#define DEVICESHADER_VARIABLE_TEXTURE2DMSARRAY         D3D11SHADER_VARIABLE_TEXTURE2DMSARRAY
#define DEVICESHADER_VARIABLE_TEXTURE3D                D3D11SHADER_VARIABLE_TEXTURE3D
#define DEVICESHADER_VARIABLE_RWTEXTURE3D              D3D11SHADER_VARIABLE_RWTEXTURE3D
#define DEVICESHADER_VARIABLE_TEXTURECUBE              D3D11SHADER_VARIABLE_TEXTURECUBE
#define DEVICESHADER_VARIABLE_TEXTURECUBEARRAY         D3D11SHADER_VARIABLE_TEXTURECUBEARRAY
#define DEVICESHADER_VARIABLE_SAMPLER                  D3D11SHADER_VARIABLE_SAMPLER
#define DEVICESHADER_VARIABLE_SAMPLER1D                D3D11SHADER_VARIABLE_SAMPLER1D
#define DEVICESHADER_VARIABLE_SAMPLER2D                D3D11SHADER_VARIABLE_SAMPLER2D
#define DEVICESHADER_VARIABLE_SAMPLER3D                D3D11SHADER_VARIABLE_SAMPLER3D
#define DEVICESHADER_VARIABLE_SAMPLERCUBE              D3D11SHADER_VARIABLE_SAMPLERCUBE
#define DEVICESHADER_VARIABLE_VERTEXSHADER             D3D11SHADER_VARIABLE_VERTEXSHADER
#define DEVICESHADER_VARIABLE_GEOMETRYSHADER           D3D11SHADER_VARIABLE_GEOMETRYSHADER
#define DEVICESHADER_VARIABLE_PIXELSHADER              D3D11SHADER_VARIABLE_PIXELSHADER
#define DEVICESHADER_VARIABLE_HULLSHADER               D3D11SHADER_VARIABLE_HULLSHADER
#define DEVICESHADER_VARIABLE_DOMAINSHADER             D3D11SHADER_VARIABLE_DOMAINSHADER
#define DEVICESHADER_VARIABLE_COMPUTESHADER            D3D11SHADER_VARIABLE_COMPUTESHADER
#define DEVICESHADER_VARIABLE_VERTEXFRAGMENT           D3D11SHADER_VARIABLE_VERTEXFRAGMENT
#define DEVICESHADER_VARIABLE_PIXELFRAGMENT            D3D11SHADER_VARIABLE_PIXELFRAGMENT
#define DEVICESHADER_VARIABLE_RASTERIZER               D3D11SHADER_VARIABLE_RASTERIZER
#define DEVICESHADER_VARIABLE_DEPTHSTENCIL             D3D11SHADER_VARIABLE_DEPTHSTENCIL
#define DEVICESHADER_VARIABLE_BLEND                    D3D11SHADER_VARIABLE_BLEND
#define DEVICESHADER_VARIABLE_RENDERTARGETVIEW         D3D11SHADER_VARIABLE_RENDERTARGETVIEW
#define DEVICESHADER_VARIABLE_DEPTHSTENCILVIEW         D3D11SHADER_VARIABLE_DEPTHSTENCILVIEW

typedef D3D11ShaderVariableFlags                      DeviceShaderVariableFlags;
#define DEVICESHADER_VARIABLEFLAG_NONE                D3D11SHADER_VARIABLEFLAG_NONE
#define DEVICESHADER_VARIABLEFLAG_USERPACKED          D3D11SHADER_VARIABLEFLAG_USERPACKED
#define DEVICESHADER_VARIABLEFLAG_USED                D3D11SHADER_VARIABLEFLAG_USED
#define DEVICESHADER_VARIABLEFLAG_INTERFACE_POINTER   D3D11SHADER_VARIABLEFLAG_INTERFACE_POINTER
#define DEVICESHADER_VARIABLEFLAG_INTERFACE_PARAMETER D3D11SHADER_VARIABLEFLAG_INTERFACE_PARAMETER

typedef D3D11ShaderTypeDesc     DeviceShaderTypeDesc;
typedef D3D11ShaderVariableDesc DeviceShaderVariableDesc;

typedef D3D11ShaderCompiler        DeviceShaderCompiler;

typedef D3D11ShaderReflectConstantBuffer DeviceShaderReflectConstantBuffer;
typedef D3D11ShaderReflectVariable       DeviceShaderReflectVariable;
typedef D3D11ShaderReflectType           DeviceShaderReflectType;

typedef D3D11Shader         DeviceShader;
typedef D3D11VertexShader   DeviceVertexShader;
typedef D3D11GeometryShader DeviceGeometryShader;
typedef D3D11PixelShader    DevicePixelShader;
typedef D3D11HullShader     DeviceHullShader;
typedef D3D11DomainShader   DeviceDomainShader;
typedef D3D11ComputeShader  DeviceComputeShader;

/////////////////////////////////////////////////////////////////////////////////
// Device2DRenderingContext Definitions
typedef D2D1Point Device2DPoint;

typedef D2D1Matrix32 Device2DMatrix32;

typedef D2D1Color Device2DColor;

typedef D2D1RenderTargetType           Device2DRenderTargetType;
#define DEVICE2D_RENDERTARGET_DEFAULT  D2D1_RENDERTARGET_DEFAULT
#define DEVICE2D_RENDERTARGET_SOFTWARE D2D1_RENDERTARGET_SOFTWARE
#define DEVICE2D_RENDERTARGET_HARDWARE D2D1_RENDERTARGET_HARDWARE

typedef D2D1RenderTargetUsage                            Device2DRenderTargetUsage;
#define DEVICE2D_RENDERTARGETUSAGE_NONE                  D2D1_RENDERTARGETUSAGE_NONE
#define DEVICE2D_RENDERTARGETUSAGE_FORCE_BITMAP_REMOTING D2D1_RENDERTARGETUSAGE_FORCE_BITMAP_REMOTING
#define DEVICE2D_RENDERTARGETUSAGE_GDI_COMPATIBLE        D2D1_RENDERTARGETUSAGE_GDI_COMPATIBLE

typedef D2D1TextDrawOptions            Device2DTextDrawOptions;
#define DEVICE2DTEXT_DRAWOPTION_NONE   D2D1TEXT_DRAWOPTION_NONE
#define DEVICE2DTEXT_DRAWOPTION_NOSNAP D2D1TEXT_DRAWOPTION_NOSNAP
#define DEVICE2DTEXT_DRAWOPTION_CLIP   D2D1TEXT_DRAWOPTION_CLIP

typedef D2D1RenderTargetDesc Device2DRenderTargetDesc;

typedef D2D1RenderingContext Device2DContext;

/////////////////////////////////////////////////////////////////////////////////
// Device2DRenderState Definitions
typedef D2D1AntialiasingMode                Device2DAntialiasingMode;
#define DEVICE2D_ANTIALIASING_PER_PRIMITIVE D2D1_ANTIALIASING_PER_PRIMITIVE
#define DEVICE2D_ANTIALIASING_ALIASED       D2D1_ANTIALIASING_ALIASED

typedef D2D1TextAntialiasingMode            Device2DTextAntialiasingMode;
#define DEVICE2DTEXT_ANTIALIASING_DEFAULT   D2D1TEXT_ANTIALIASING_DEFAULT
#define DEVICE2DTEXT_ANTIALIASING_CLEARTYPE D2D1TEXT_ANTIALIASING_CLEARTYPE
#define DEVICE2DTEXT_ANTIALIASING_GRAYSCALE D2D1TEXT_ANTIALIASING_GRAYSCALE
#define DEVICE2DTEXT_ANTIALIASING_ALIASED   D2D1TEXT_ANTIALIASING_ALIASED

typedef D2D1Tag Device2DTag;

typedef D2D1RenderStateDesc Device2DRenderStateDesc;

typedef D2D1TextPixelGeometry           Device2DTextPixelGeometry;
#define DEVICE2DTEXT_PIXELGEOMETRY_FLAT D2D1TEXT_PIXELGEOMETRY_FLAT
#define DEVICE2DTEXT_PIXELGEOMETRY_RGB  D2D1TEXT_PIXELGEOMETRY_RGB
#define DEVICE2DTEXT_PIXELGEOMETRY_BGR  D2D1TEXT_PIXELGEOMETRY_BGR

typedef D2D1TextRenderingMode                                  Device2DTextRenderingMode;
#define DEVICE2DTEXT_RENDERINGMODE_DEFAULT                     D2D1TEXT_RENDERINGMODE_DEFAULT
#define DEVICE2DTEXT_RENDERINGMODE_ALIASED                     D2D1TEXT_RENDERINGMODE_ALIASED
#define DEVICE2DTEXT_RENDERINGMODE_OUTLINE                     D2D1TEXT_RENDERINGMODE_OUTLINE
#define DEVICE2DTEXT_RENDERINGMODE_CLEARTYPE_GDI_CLASSIC       D2D1TEXT_RENDERINGMODE_CLEARTYPE_GDI_CLASSIC
#define DEVICE2DTEXT_RENDERINGMODE_CLEARTYPE_GDI_NATURAL       D2D1TEXT_RENDERINGMODE_CLEARTYPE_GDI_NATURAL
#define DEVICE2DTEXT_RENDERINGMODE_CLEARTYPE_NATURAL           D2D1TEXT_RENDERINGMODE_CLEARTYPE_NATURAL
#define DEVICE2DTEXT_RENDERINGMODE_CLEARTYPE_NATURAL_SYMMETRIC D2D1TEXT_RENDERINGMODE_CLEARTYPE_NATURAL_SYMMETRIC

typedef D2D1TextRenderStateDesc Device2DTextRenderStateDesc;

typedef D2D1RenderState     Device2DRenderState;
typedef D2D1TextRenderState Device2DTextRenderState;

/////////////////////////////////////////////////////////////////////////////////
// Device2DStrokeStyle Definitions
typedef D2D1StrokeCapStyle               Device2DStrokeCapStyle;
#define DEVICE2DSTROKE_CAPSTYLE_FLAT     D2D1STROKE_CAPSTYLE_FLAT
#define DEVICE2DSTROKE_CAPSTYLE_SQUARE   D2D1STROKE_CAPSTYLE_SQUARE
#define DEVICE2DSTROKE_CAPSTYLE_ROUND    D2D1STROKE_CAPSTYLE_ROUND
#define DEVICE2DSTROKE_CAPSTYLE_TRIANGLE D2D1STROKE_CAPSTYLE_TRIANGLE

typedef D2D1StrokeLineJoin                     Device2DStrokeLineJoin;
#define DEVICE2DSTROKE_LINEJOIN_MITER          D2D1STROKE_LINEJOIN_MITER
#define DEVICE2DSTROKE_LINEJOIN_BEVEL          D2D1STROKE_LINEJOIN_BEVEL
#define DEVICE2DSTROKE_LINEJOIN_ROUND          D2D1STROKE_LINEJOIN_ROUND
#define DEVICE2DSTROKE_LINEJOIN_MITER_OR_BEVEL D2D1STROKE_LINEJOIN_MITER_OR_BEVEL

typedef D2D1StrokeDashStyle                 Device2DStrokeDashStyle;
#define DEVICE2DSTROKE_DASHSTYLE_SOLID      D2D1STROKE_DASHSTYLE_SOLID
#define DEVICE2DSTROKE_DASHSTYLE_DASH       D2D1STROKE_DASHSTYLE_DASH
#define DEVICE2DSTROKE_DASHSTYLE_DOT        D2D1STROKE_DASHSTYLE_DOT
#define DEVICE2DSTROKE_DASHSTYLE_DASHDOT    D2D1STROKE_DASHSTYLE_DASHDOT
#define DEVICE2DSTROKE_DASHSTYLE_DASHDOTDOT D2D1STROKE_DASHSTYLE_DASHDOTDOT
#define DEVICE2DSTROKE_DASHSTYLE_CUSTOM     D2D1STROKE_DASHSTYLE_CUSTOM

typedef D2D1StrokeStyleDesc Device2DStrokeStyleDesc;

typedef D2D1StrokeStyle Device2DStrokeStyle;

/////////////////////////////////////////////////////////////////////////////////
// Device2DBitmap Definitions
typedef D2D1PointI     Device2DPointI;
typedef D2D1RectangleI Device2DRectangleI;

typedef D2D1BitmapInterpolationMode          Device2DBitmapInterpolationMode;
#define DEVICE2DBITMAP_INTERPOLATION_NEAREST D2D1BITMAP_INTERPOLATION_NEAREST
#define DEVICE2DBITMAP_INTERPOLATION_LINEAR  D2D1BITMAP_INTERPOLATION_LINEAR

typedef D2D1BitmapOpacityMaskContent                  Device2DBitmapOpacityMaskContent;
#define DEVICE2DBITMAP_OPACITYMASK_GRAPHICS           D2D1BITMAP_OPACITYMASK_GRAPHICS
#define DEVICE2DBITMAP_OPACITYMASK_TEXT_NATURAL       D2D1BITMAP_OPACITYMASK_TEXT_NATURAL
#define DEVICE2DBITMAP_OPACITYMASK_TEXT_GDICOMPATIBLE D2D1BITMAP_OPACITYMASK_TEXT_GDICOMPATIBLE

typedef D2D1BitmapAlphaMode                    Device2DBitmapAlphaMode;
#define DEVICE2DBITMAP_ALPHAMODE_UNKNOWN       D2D1BITMAP_ALPHAMODE_UNKNOWN
#define DEVICE2DBITMAP_ALPHAMODE_PREMULTIPLIED D2D1BITMAP_ALPHAMODE_PREMULTIPLIED
#define DEVICE2DBITMAP_ALPHAMODE_STRAIGHT      D2D1BITMAP_ALPHAMODE_STRAIGHT
#define DEVICE2DBITMAP_ALPHAMODE_IGNORE        D2D1BITMAP_ALPHAMODE_IGNORE

typedef D2D1BitmapDesc Device2DBitmapDesc;

typedef D2D1Bitmap Device2DBitmap;

/////////////////////////////////////////////////////////////////////////////////
// Device2DBrush Definitions
typedef D2D1BrushGamma          Device2DBrushGamma;
#define DEVICE2DBRUSH_GAMMA_2_2 D2D1BRUSH_GAMMA_2_2
#define DEVICE2DBRUSH_GAMMA_1_0 D2D1BRUSH_GAMMA_1_0

typedef D2D1BrushWrapMode             Device2DBrushWrapMode;
#define DEVICE2DBRUSH_WRAPMODE_CLAMP  D2D1BRUSH_WRAPMODE_CLAMP
#define DEVICE2DBRUSH_WRAPMODE_REPEAT D2D1BRUSH_WRAPMODE_REPEAT
#define DEVICE2DBRUSH_WRAPMODE_MIRROR D2D1BRUSH_WRAPMODE_MIRROR

#define DEVICE2DGRADIENT_MAX_STOPS D2D1GRADIENT_MAX_STOPS
typedef D2D1GradientStop           Device2DGradientStop;
typedef D2D1GradientDesc           Device2DGradientDesc;

typedef D2D1BrushDesc               Device2DBrushDesc;
typedef D2D1BrushLinearGradientDesc Device2DBrushLinearGradientDesc;
typedef D2D1BrushRadialGradientDesc Device2DBrushRadialGradientDesc;
typedef D2D1BrushBitmapDesc         Device2DBrushBitmapDesc;

typedef D2D1BrushType                  Device2DBrushType;
#define DEVICE2DBRUSH_SOLID_COLOR     D2D1BRUSH_SOLID_COLOR
#define DEVICE2DBRUSH_GRADIENT_LINEAR D2D1BRUSH_GRADIENT_LINEAR
#define DEVICE2DBRUSH_GRADIENT_RADIAL D2D1BRUSH_GRADIENT_RADIAL
#define DEVICE2DBRUSH_BITMAP          D2D1BRUSH_BITMAP

typedef D2D1Brush               Device2DBrush;
typedef D2D1SolidColorBrush     Device2DSolidColorBrush;
typedef D2D1GradientBrush       Device2DGradientBrush;
typedef D2D1LinearGradientBrush Device2DLinearGradientBrush;
typedef D2D1RadialGradientBrush Device2DRadialGradientBrush;
typedef D2D1BitmapBrush         Device2DBitmapBrush;

/////////////////////////////////////////////////////////////////////////////////
// Device2DMesh Definitions
typedef D2D1Triangle Device2DTriangle;

typedef D2D1Mesh Device2DMesh;

/////////////////////////////////////////////////////////////////////////////////
// Device2DGeometry Definitions
typedef D2D1GeometryRelation                  Device2DGeometryRelation;
#define DEVICE2DGEOMETRY_RELATION_UNKNOWN     D2D1GEOMETRY_RELATION_UNKNOWN
#define DEVICE2DGEOMETRY_RELATION_DISJOINT    D2D1GEOMETRY_RELATION_DISJOINT
#define DEVICE2DGEOMETRY_RELATION_ISCONTAINED D2D1GEOMETRY_RELATION_ISCONTAINED
#define DEVICE2DGEOMETRY_RELATION_CONTAINS    D2D1GEOMETRY_RELATION_CONTAINS
#define DEVICE2DGEOMETRY_RELATION_OVERLAP     D2D1GEOMETRY_RELATION_OVERLAP

typedef D2D1GeometryCombineMode            Device2DGeometryCombineMode;
#define DEVICE2DGEOMETRY_COMBINE_UNION     D2D1GEOMETRY_COMBINE_UNION
#define DEVICE2DGEOMETRY_COMBINE_INTERSECT D2D1GEOMETRY_COMBINE_INTERSECT
#define DEVICE2DGEOMETRY_COMBINE_EXCLUDE   D2D1GEOMETRY_COMBINE_EXCLUDE
#define DEVICE2DGEOMETRY_COMBINE_XOR       D2D1GEOMETRY_COMBINE_XOR

typedef D2D1GeometrySimplifyOption                 Device2DGeometrySimplifyOption;
#define DEVICE2DGEOMETRY_SIMPLIFY_CUBICS_AND_LINES D2D1GEOMETRY_SIMPLIFY_CUBICS_AND_LINES
#define DEVICE2DGEOMETRY_SIMPLIFY_LINES_ONLY       D2D1GEOMETRY_SIMPLIFY_LINES_ONLY

typedef D2D1GeometryFillMode            Device2DGeometryFillMode;
#define DEVICE2DGEOMETRY_FILL_ALTERNATE D2D1GEOMETRY_FILL_ALTERNATE
#define DEVICE2DGEOMETRY_FILL_WINDING   D2D1GEOMETRY_FILL_WINDING

typedef D2D1GeometrySegmentFlag                        Device2DGeometrySegmentFlag;
#define DEVICE2DGEOMETRY_SEGMENT_NONE                  D2D1GEOMETRY_SEGMENT_NONE
#define DEVICE2DGEOMETRY_SEGMENT_FORCE_UNSTROKED       D2D1GEOMETRY_SEGMENT_FORCE_UNSTROKED
#define DEVICE2DGEOMETRY_SEGMENT_FORCE_ROUND_LINE_JOIN D2D1GEOMETRY_SEGMENT_FORCE_ROUND_LINE_JOIN

typedef D2D1GeometryType                    Device2DGeometryType;
#define DEVICE2DGEOMETRY_RECTANGLE         D2D1GEOMETRY_RECTANGLE
#define DEVICE2DGEOMETRY_ROUNDED_RECTANGLE D2D1GEOMETRY_ROUNDED_RECTANGLE
#define DEVICE2DGEOMETRY_ELLIPSE           D2D1GEOMETRY_ELLIPSE
#define DEVICE2DGEOMETRY_PATH              D2D1GEOMETRY_PATH
#define DEVICE2DGEOMETRY_TRANSFORMED       D2D1GEOMETRY_TRANSFORMED
#define DEVICE2DGEOMETRY_GROUP             D2D1GEOMETRY_GROUP

typedef D2D1Rectangle        Device2DRectangle;
typedef D2D1RoundedRectangle Device2DRoundedRectangle;
typedef D2D1Ellipse          Device2DEllipse;

typedef D2D1BezierSegment          Device2DBezierSegment;
typedef D2D1QuadraticBezierSegment Device2DQuadraticBezierSegment;

typedef D2D1ArcSweepDirection                  Device2DArcSweepDirection;
#define DEVICE2DARC_SWEEPDIR_COUNTER_CLOCKWISE D2D1ARC_SWEEPDIR_COUNTER_CLOCKWISE
#define DEVICE2DARC_SWEEPDIR_CLOCKWISE         D2D1ARC_SWEEPDIR_CLOCKWISE

typedef D2D1ArcSize            Device2DArcSize;
#define DEVICE2DARC_SIZE_SMALL D2D1ARC_SIZE_SMALL
#define DEVICE2DARC_SIZE_LARGE D2D1ARC_SIZE_LARGE

typedef D2D1ArcSegment             Device2DArcSegment;

typedef D2D1Geometry                 Device2DGeometry;
typedef D2D1RectangleGeometry        Device2DRectangleGeometry;
typedef D2D1RoundedRectangleGeometry Device2DRoundedRectangleGeometry;
typedef D2D1EllipseGeometry          Device2DEllipseGeometry;
typedef D2D1PathGeometry             Device2DPathGeometry;
typedef D2D1TransformedGeometry      Device2DTransformedGeometry;
typedef D2D1GeometryGroup            Device2DGeometryGroup;

/////////////////////////////////////////////////////////////////////////////////
// Device2DLayer Definitions
typedef D2D1LayerOptions                    Device2DLayerOptions;
#define DEVICE2DLAYER_OPTION_NONE           D2D1LAYER_OPTION_NONE
#define DEVICE2DLAYER_OPTION_CLEARTYPE_INIT D2D1LAYER_OPTION_CLEARTYPE_INIT

typedef D2D1LayerParameters Device2DLayerParameters;
typedef D2D1Layer           Device2DLayer;

/////////////////////////////////////////////////////////////////////////////////
// Device2DText Definitions
#define DEVICE2DFONT_FAMILY_NAME_MAX_LENGTH D2D1_FONTFAMILY_NAME_MAX_LENGTH
#define DEVICE2DFONT_FAMILY_ARIAL           D2D1_FONTFAMILY_ARIAL

typedef D2D1FontWeight                  Device2DFontWeight;
#define DEVICE2DFONT_WEIGHT_THIN        D2D1FONT_WEIGHT_THIN
#define DEVICE2DFONT_WEIGHT_EXTRALIGHT  D2D1FONT_WEIGHT_EXTRALIGHT
#define DEVICE2DFONT_WEIGHT_LIGHT       D2D1FONT_WEIGHT_LIGHT
#define DEVICE2DFONT_WEIGHT_NORMAL      D2D1FONT_WEIGHT_NORMAL
#define DEVICE2DFONT_WEIGHT_MEDIUM      D2D1FONT_WEIGHT_MEDIUM
#define DEVICE2DFONT_WEIGHT_SEMIBOLD    D2D1FONT_WEIGHT_SEMIBOLD
#define DEVICE2DFONT_WEIGHT_BOLD        D2D1FONT_WEIGHT_BOLD
#define DEVICE2DFONT_WEIGHT_EXTRABOLD   D2D1FONT_WEIGHT_EXTRABOLD
#define DEVICE2DFONT_WEIGHT_BLACK       D2D1FONT_WEIGHT_BLACK
#define DEVICE2DFONT_WEIGHT_EXTRA_BLACK D2D1FONT_WEIGHT_EXTRA_BLACK

typedef D2D1FontStyle              Device2DFontStyle;
#define DEVICE2DFONT_STYLE_NORMAL  D2D1FONT_STYLE_NORMAL
#define DEVICE2DFONT_STYLE_OBLIQUE D2D1FONT_STYLE_OBLIQUE
#define DEVICE2DFONT_STYLE_ITALIC  D2D1FONT_STYLE_ITALIC

typedef D2D1FontStretch                     Device2DFontStretch;
#define DEVICE2DFONT_STRETCH_UNDEFINED      D2D1FONT_STRETCH_UNDEFINED
#define DEVICE2DFONT_STRETCH_ULTRACONDENSED D2D1FONT_STRETCH_ULTRACONDENSED
#define DEVICE2DFONT_STRETCH_EXTRACONDENSED D2D1FONT_STRETCH_EXTRACONDENSED
#define DEVICE2DFONT_STRETCH_CONDENSED      D2D1FONT_STRETCH_CONDENSED
#define DEVICE2DFONT_STRETCH_SEMICONDENSED  D2D1FONT_STRETCH_SEMICONDENSED
#define DEVICE2DFONT_STRETCH_NORMAL         D2D1FONT_STRETCH_NORMAL
#define DEVICE2DFONT_STRETCH_SEMIEXPANDED   D2D1FONT_STRETCH_SEMIEXPANDED
#define DEVICE2DFONT_STRETCH_EXPANDED       D2D1FONT_STRETCH_EXPANDED
#define DEVICE2DFONT_STRETCH_EXTRAEXPANDED  D2D1FONT_STRETCH_EXTRAEXPANDED
#define DEVICE2DFONT_STRETCH_ULTRAEXPANDED  D2D1FONT_STRETCH_ULTRAEXPANDED

typedef D2D1FontInfoStringID                         Device2DFontInfoStringID;
#define DEVICE2DFONT_INFOSTRING_NONE                 D2D1FONT_INFOSTRING_NONE
#define DEVICE2DFONT_INFOSTRING_COPYRIGHT            D2D1FONT_INFOSTRING_COPYRIGHT
#define DEVICE2DFONT_INFOSTRING_VERSION              D2D1FONT_INFOSTRING_VERSION
#define DEVICE2DFONT_INFOSTRING_TRADEMARK            D2D1FONT_INFOSTRING_TRADEMARK
#define DEVICE2DFONT_INFOSTRING_MANUFACTURER         D2D1FONT_INFOSTRING_MANUFACTURER
#define DEVICE2DFONT_INFOSTRING_DESIGNER             D2D1FONT_INFOSTRING_DESIGNER
#define DEVICE2DFONT_INFOSTRING_DESIGNER_URL         D2D1FONT_INFOSTRING_DESIGNER_URL
#define DEVICE2DFONT_INFOSTRING_DESCRIPTION          D2D1FONT_INFOSTRING_DESCRIPTION
#define DEVICE2DFONT_INFOSTRING_VENDOR_URL           D2D1FONT_INFOSTRING_VENDOR_URL
#define DEVICE2DFONT_INFOSTRING_LICENSE_DESCRIPTION  D2D1FONT_INFOSTRING_LICENSE_DESCRIPTION
#define DEVICE2DFONT_INFOSTRING_LICENSE_URL          D2D1FONT_INFOSTRING_LICENSE_URL
#define DEVICE2DFONT_INFOSTRING_WIN32_FAMILYNAMES    D2D1FONT_INFOSTRING_WIN32_FAMILYNAMES
#define DEVICE2DFONT_INFOSTRING_WIN32_SUBFAMILYNAMES D2D1FONT_INFOSTRING_WIN32_SUBFAMILYNAMES
#define DEVICE2DFONT_INFOSTRING_PREF_FAMILYNAMES     D2D1FONT_INFOSTRING_PREF_FAMILYNAMES
#define DEVICE2DFONT_INFOSTRING_PREF_SUBFAMILYNAMES  D2D1FONT_INFOSTRING_PREF_SUBFAMILYNAMES
#define DEVICE2DFONT_INFOSTRING_SAMPLE_TEXT          D2D1FONT_INFOSTRING_SAMPLE_TEXT

typedef D2D1FontSimulation              Device2DFontSimulation;
#define DEVICE2DFONT_SIMULATION_NONE    D2D1FONT_SIMULATION_NONE
#define DEVICE2DFONT_SIMULATION_BOLD    D2D1FONT_SIMULATION_BOLD
#define DEVICE2DFONT_SIMULATION_OBLIQUE D2D1FONT_SIMULATION_OBLIQUE

typedef D2D1FontFaceType                      Device2DFontFaceType;
#define DEVICE2DFONT_FACE_CFF                 D2D1FONT_FACE_CFF
#define DEVICE2DFONT_FACE_TRUETYPE            D2D1FONT_FACE_TRUETYPE
#define DEVICE2DFONT_FACE_TRUETYPE_COLLECTION D2D1FONT_FACE_TRUETYPE_COLLECTION
#define DEVICE2DFONT_FACE_TYPE1               D2D1FONT_FACE_TYPE1
#define DEVICE2DFONT_FACE_VECTOR              D2D1FONT_FACE_VECTOR
#define DEVICE2DFONT_FACE_BITMAP              D2D1FONT_FACE_BITMAP
#define DEVICE2DFONT_FACE_UNKNOWN             D2D1FONT_FACE_UNKNOWN

typedef D2D1FontMetrics      Device2DFontMetrics;
typedef D2D1FontGlyphMetrics Device2DFontGlyphMetrics;
typedef D2D1FontGlyphOffset  Device2DFontGlyphOffset;

typedef D2D1FontCollection Device2DFontCollection;
typedef D2D1FontFamily     Device2DFontFamily;
typedef D2D1Font           Device2DFont;
typedef D2D1FontList       Device2DFontList;
typedef D2D1FontFace       Device2DFontFace;

typedef D2D1TextMeasuringMode                  Device2DTextMeasuringMode;
#define DEVICE2DTEXT_MEASURING_NATURAL     D2D1TEXT_MEASURING_NATURAL
#define DEVICE2DTEXT_MEASURING_GDI_CLASSIC D2D1TEXT_MEASURING_GDI_CLASSIC
#define DEVICE2DTEXT_MEASURING_GDI_NATURAL D2D1TEXT_MEASURING_GDI_NATURAL

typedef D2D1TextFlowDirection                 Device2DTextFlowDirection;
#define DEVICE2DTEXT_FLOWDIRECTION_TOP_BOTTOM D2D1TEXT_FLOWDIRECTION_TOP_BOTTOM

typedef D2D1TextReadingDirection                 Device2DTextReadingDirection;
#define DEVICE2DTEXT_READINGDIRECTION_LEFT_RIGHT D2D1TEXT_READINGDIRECTION_LEFT_RIGHT
#define DEVICE2DTEXT_READINGDIRECTION_RIGHT_LEFT D2D1TEXT_READINGDIRECTION_RIGHT_LEFT

typedef D2D1TextLineSpacingMethod              Device2DTextLineSpacingMethod;
#define DEVICE2DTEXT_LINESPACING_DEFAULT D2D1TEXT_LINESPACING_DEFAULT
#define DEVICE2DTEXT_LINESPACING_UNIFORM D2D1TEXT_LINESPACING_UNIFORM

typedef D2D1TextAlignment               Device2DTextAlignment;
#define DEVICE2DTEXT_ALIGNMENT_LEADING  D2D1TEXT_ALIGNMENT_LEADING
#define DEVICE2DTEXT_ALIGNMENT_TRAILING D2D1TEXT_ALIGNMENT_TRAILING
#define DEVICE2DTEXT_ALIGNMENT_CENTER   D2D1TEXT_ALIGNMENT_CENTER

typedef D2D1TextParagraphAlignment             Device2DTextParagraphAlignment;
#define DEVICE2DTEXT_PARAGRAPHALIGNMENT_NEAR   D2D1TEXT_PARAGRAPHALIGNMENT_NEAR
#define DEVICE2DTEXT_PARAGRAPHALIGNMENT_FAR    D2D1TEXT_PARAGRAPHALIGNMENT_FAR
#define DEVICE2DTEXT_PARAGRAPHALIGNMENT_CENTER D2D1TEXT_PARAGRAPHALIGNMENT_CENTER

typedef D2D1TextTrimmingGranularity                Device2DTextTrimmingGranularity;
#define DEVICE2DTEXT_TRIMMINGGRANULARITY_NONE      D2D1TEXT_TRIMMINGGRANULARITY_NONE
#define DEVICE2DTEXT_TRIMMINGGRANULARITY_CHARACTER D2D1TEXT_TRIMMINGGRANULARITY_CHARACTER
#define DEVICE2DTEXT_TRIMMINGGRANULARITY_WORD      D2D1TEXT_TRIMMINGGRANULARITY_WORD

typedef D2D1TextWordWrapping           Device2DTextWordWrapping;
#define DEVICE2DTEXT_WORDWRAPPING_NONE D2D1TEXT_WORDWRAPPING_NONE
#define DEVICE2DTEXT_WORDWRAPPING_WRAP D2D1TEXT_WORDWRAPPING_WRAP

typedef D2D1TextBreakCondition                    Device2DTextBreakCondition;
#define DEVICE2DTEXT_BREAKCONDITION_NEUTRAL       D2D1TEXT_BREAKCONDITION_NEUTRAL
#define DEVICE2DTEXT_BREAKCONDITION_CAN_BREAK     D2D1TEXT_BREAKCONDITION_CAN_BREAK
#define DEVICE2DTEXT_BREAKCONDITION_MAY_NOT_BREAK D2D1TEXT_BREAKCONDITION_MAY_NOT_BREAK
#define DEVICE2DTEXT_BREAKCONDITION_MUST_BREAK    D2D1TEXT_BREAKCONDITION_MUST_BREAK

typedef D2D1TextRange               Device2DTextRange;
typedef D2D1TextMetrics             Device2DTextMetrics;
typedef D2D1TextOverhangMetrics     Device2DTextOverhangMetrics;
typedef D2D1TextLineMetrics         Device2DTextLineMetrics;
typedef D2D1TextClusterMetrics      Device2DTextClusterMetrics;
typedef D2D1TextHitTestMetrics      Device2DTextHitTestMetrics;
typedef D2D1TextInlineObjectMetrics Device2DTextInlineObjectMetrics;

typedef D2D1TextFormat       Device2DTextFormat;
typedef D2D1TextLayout       Device2DTextLayout;
typedef D2D1TextInlineObject Device2DTextInlineObject;

#elif defined(RENDERER_USE_OPENGL)
/////////////////////////////////////////////////////////////////////////////////

    /////////////////////////////////////////////////////////

#elif defined(RENDERER_USE_SOFTWARE)
/////////////////////////////////////////////////////////////////////////////////

    /////////////////////////////////////////////////////////

#endif

/////////////////////////////////////////////////////////////////////////////////
// Backward Includes (Inlines & Templates)
#include "DeviceRenderer.inl"

/////////////////////////////////////////////////////////////////////////////////
// Header end
#endif // SCARAB_ENGINE_RENDERING_DEVICERENDERER_H

